package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_DSP_STATE {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_DSP_STATE(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_DSP_STATE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_DSP_STATE obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_DSP_STATE(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInstance(SWIGTYPE_p_void value) {
    FMODStudioJNI.FMOD_DSP_STATE_instance_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getInstance() {
    long cPtr = FMODStudioJNI.FMOD_DSP_STATE_instance_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setPlugindata(SWIGTYPE_p_void value) {
    FMODStudioJNI.FMOD_DSP_STATE_plugindata_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getPlugindata() {
    long cPtr = FMODStudioJNI.FMOD_DSP_STATE_plugindata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setChannelmask(long value) {
    FMODStudioJNI.FMOD_DSP_STATE_channelmask_set(swigCPtr, this, value);
  }

  public long getChannelmask() {
    return FMODStudioJNI.FMOD_DSP_STATE_channelmask_get(swigCPtr, this);
  }

  public void setSource_speakermode(FMOD_SPEAKERMODE value) {
    FMODStudioJNI.FMOD_DSP_STATE_source_speakermode_set(swigCPtr, this, value.swigValue());
  }

  public FMOD_SPEAKERMODE getSource_speakermode() {
    return FMOD_SPEAKERMODE.swigToEnum(FMODStudioJNI.FMOD_DSP_STATE_source_speakermode_get(swigCPtr, this));
  }

  public void setSidechaindata(SWIGTYPE_p_float value) {
    FMODStudioJNI.FMOD_DSP_STATE_sidechaindata_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getSidechaindata() {
    long cPtr = FMODStudioJNI.FMOD_DSP_STATE_sidechaindata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setSidechainchannels(int value) {
    FMODStudioJNI.FMOD_DSP_STATE_sidechainchannels_set(swigCPtr, this, value);
  }

  public int getSidechainchannels() {
    return FMODStudioJNI.FMOD_DSP_STATE_sidechainchannels_get(swigCPtr, this);
  }

  public void setFunctions(FMOD_DSP_STATE_FUNCTIONS value) {
    FMODStudioJNI.FMOD_DSP_STATE_functions_set(swigCPtr, this, FMOD_DSP_STATE_FUNCTIONS.getCPtr(value), value);
  }

  public FMOD_DSP_STATE_FUNCTIONS getFunctions() {
    long cPtr = FMODStudioJNI.FMOD_DSP_STATE_functions_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_DSP_STATE_FUNCTIONS(cPtr, false);
  }

  public void setSystemobject(int value) {
    FMODStudioJNI.FMOD_DSP_STATE_systemobject_set(swigCPtr, this, value);
  }

  public int getSystemobject() {
    return FMODStudioJNI.FMOD_DSP_STATE_systemobject_get(swigCPtr, this);
  }

  public FMOD_DSP_STATE() {
    this(FMODStudioJNI.new_FMOD_DSP_STATE(), true);
  }

}
