package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_DSP_PARAMETER_DESC_FLOAT {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_DSP_PARAMETER_DESC_FLOAT(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_DSP_PARAMETER_DESC_FLOAT obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_DSP_PARAMETER_DESC_FLOAT obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_DSP_PARAMETER_DESC_FLOAT(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMin(float value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_FLOAT_min_set(swigCPtr, this, value);
  }

  public float getMin() {
    return FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_FLOAT_min_get(swigCPtr, this);
  }

  public void setMax(float value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_FLOAT_max_set(swigCPtr, this, value);
  }

  public float getMax() {
    return FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_FLOAT_max_get(swigCPtr, this);
  }

  public void setDefaultval(float value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_FLOAT_defaultval_set(swigCPtr, this, value);
  }

  public float getDefaultval() {
    return FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_FLOAT_defaultval_get(swigCPtr, this);
  }

  public void setMapping(FMOD_DSP_PARAMETER_FLOAT_MAPPING value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_FLOAT_mapping_set(swigCPtr, this, FMOD_DSP_PARAMETER_FLOAT_MAPPING.getCPtr(value), value);
  }

  public FMOD_DSP_PARAMETER_FLOAT_MAPPING getMapping() {
    long cPtr = FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_FLOAT_mapping_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_DSP_PARAMETER_FLOAT_MAPPING(cPtr, false);
  }

  public FMOD_DSP_PARAMETER_DESC_FLOAT() {
    this(FMODStudioJNI.new_FMOD_DSP_PARAMETER_DESC_FLOAT(), true);
  }

}
