package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_OUTPUT_DESCRIPTION {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_OUTPUT_DESCRIPTION(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_OUTPUT_DESCRIPTION obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_OUTPUT_DESCRIPTION obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_OUTPUT_DESCRIPTION(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setApiversion(long value) {
    FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_apiversion_set(swigCPtr, this, value);
  }

  public long getApiversion() {
    return FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_apiversion_get(swigCPtr, this);
  }

  public void setName(String value) {
    FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_name_get(swigCPtr, this);
  }

  public void setVersion(long value) {
    FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_version_set(swigCPtr, this, value);
  }

  public long getVersion() {
    return FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_version_get(swigCPtr, this);
  }

  public void setMethod(long value) {
    FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_method_set(swigCPtr, this, value);
  }

  public long getMethod() {
    return FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_method_get(swigCPtr, this);
  }

  public void setGetnumdrivers(SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_int__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_getnumdrivers_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_int__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_int__FMOD_RESULT getGetnumdrivers() {
    long cPtr = FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_getnumdrivers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_int__FMOD_RESULT(cPtr, false);
  }

  public void setGetdriverinfo(SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_int_p_char_int_p_struct_FMOD_GUID_p_int_p_enum_FMOD_SPEAKERMODE_p_int__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_getdriverinfo_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_int_p_char_int_p_struct_FMOD_GUID_p_int_p_enum_FMOD_SPEAKERMODE_p_int__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_int_p_char_int_p_struct_FMOD_GUID_p_int_p_enum_FMOD_SPEAKERMODE_p_int__FMOD_RESULT getGetdriverinfo() {
    long cPtr = FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_getdriverinfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_int_p_char_int_p_struct_FMOD_GUID_p_int_p_enum_FMOD_SPEAKERMODE_p_int__FMOD_RESULT(cPtr, false);
  }

  public void setInit(SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_int_unsigned_int_p_int_p_enum_FMOD_SPEAKERMODE_p_int_p_enum_FMOD_SOUND_FORMAT_int_p_int_p_int_p_void__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_init_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_int_unsigned_int_p_int_p_enum_FMOD_SPEAKERMODE_p_int_p_enum_FMOD_SOUND_FORMAT_int_p_int_p_int_p_void__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_int_unsigned_int_p_int_p_enum_FMOD_SPEAKERMODE_p_int_p_enum_FMOD_SOUND_FORMAT_int_p_int_p_int_p_void__FMOD_RESULT getInit() {
    long cPtr = FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_init_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_int_unsigned_int_p_int_p_enum_FMOD_SPEAKERMODE_p_int_p_enum_FMOD_SOUND_FORMAT_int_p_int_p_int_p_void__FMOD_RESULT(cPtr, false);
  }

  public void setStart(SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_start_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT getStart() {
    long cPtr = FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_start_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT(cPtr, false);
  }

  public void setStop(SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_stop_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT getStop() {
    long cPtr = FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_stop_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT(cPtr, false);
  }

  public void setClose(SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_close_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT getClose() {
    long cPtr = FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_close_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT(cPtr, false);
  }

  public void setUpdate(SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_update_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT getUpdate() {
    long cPtr = FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_update_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT(cPtr, false);
  }

  public void setGethandle(SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_p_void__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_gethandle_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_p_void__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_p_void__FMOD_RESULT getGethandle() {
    long cPtr = FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_gethandle_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_p_void__FMOD_RESULT(cPtr, false);
  }

  public void setMixer(SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_mixer_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT getMixer() {
    long cPtr = FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_mixer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT(cPtr, false);
  }

  public void setObject3dgetinfo(SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_int__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_object3dgetinfo_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_int__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_int__FMOD_RESULT getObject3dgetinfo() {
    long cPtr = FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_object3dgetinfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_int__FMOD_RESULT(cPtr, false);
  }

  public void setObject3dalloc(SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_p_void__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_object3dalloc_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_p_void__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_p_void__FMOD_RESULT getObject3dalloc() {
    long cPtr = FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_object3dalloc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_p_void__FMOD_RESULT(cPtr, false);
  }

  public void setObject3dfree(SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_void__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_object3dfree_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_void__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_void__FMOD_RESULT getObject3dfree() {
    long cPtr = FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_object3dfree_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_void__FMOD_RESULT(cPtr, false);
  }

  public void setObject3dupdate(SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_void_p_q_const__struct_FMOD_OUTPUT_OBJECT3DINFO__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_object3dupdate_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_void_p_q_const__struct_FMOD_OUTPUT_OBJECT3DINFO__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_void_p_q_const__struct_FMOD_OUTPUT_OBJECT3DINFO__FMOD_RESULT getObject3dupdate() {
    long cPtr = FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_object3dupdate_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_void_p_q_const__struct_FMOD_OUTPUT_OBJECT3DINFO__FMOD_RESULT(cPtr, false);
  }

  public void setOpenport(SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_enum_FMOD_PORT_TYPE_unsigned_long_long_p_int_p_int_p_int_p_enum_FMOD_SOUND_FORMAT__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_openport_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_enum_FMOD_PORT_TYPE_unsigned_long_long_p_int_p_int_p_int_p_enum_FMOD_SOUND_FORMAT__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_enum_FMOD_PORT_TYPE_unsigned_long_long_p_int_p_int_p_int_p_enum_FMOD_SOUND_FORMAT__FMOD_RESULT getOpenport() {
    long cPtr = FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_openport_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_enum_FMOD_PORT_TYPE_unsigned_long_long_p_int_p_int_p_int_p_enum_FMOD_SOUND_FORMAT__FMOD_RESULT(cPtr, false);
  }

  public void setCloseport(SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_int__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_closeport_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_int__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_int__FMOD_RESULT getCloseport() {
    long cPtr = FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_closeport_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_int__FMOD_RESULT(cPtr, false);
  }

  public void setDevicelistchanged(SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_devicelistchanged_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT getDevicelistchanged() {
    long cPtr = FMODStudioJNI.FMOD_OUTPUT_DESCRIPTION_devicelistchanged_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT(cPtr, false);
  }

  public FMOD_OUTPUT_DESCRIPTION() {
    this(FMODStudioJNI.new_FMOD_OUTPUT_DESCRIPTION(), true);
  }

}
