package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_TREMOLO {
  public final static FMOD_DSP_TREMOLO FMOD_DSP_TREMOLO_FREQUENCY = new FMOD_DSP_TREMOLO("FMOD_DSP_TREMOLO_FREQUENCY");
  public final static FMOD_DSP_TREMOLO FMOD_DSP_TREMOLO_DEPTH = new FMOD_DSP_TREMOLO("FMOD_DSP_TREMOLO_DEPTH");
  public final static FMOD_DSP_TREMOLO FMOD_DSP_TREMOLO_SHAPE = new FMOD_DSP_TREMOLO("FMOD_DSP_TREMOLO_SHAPE");
  public final static FMOD_DSP_TREMOLO FMOD_DSP_TREMOLO_SKEW = new FMOD_DSP_TREMOLO("FMOD_DSP_TREMOLO_SKEW");
  public final static FMOD_DSP_TREMOLO FMOD_DSP_TREMOLO_DUTY = new FMOD_DSP_TREMOLO("FMOD_DSP_TREMOLO_DUTY");
  public final static FMOD_DSP_TREMOLO FMOD_DSP_TREMOLO_SQUARE = new FMOD_DSP_TREMOLO("FMOD_DSP_TREMOLO_SQUARE");
  public final static FMOD_DSP_TREMOLO FMOD_DSP_TREMOLO_PHASE = new FMOD_DSP_TREMOLO("FMOD_DSP_TREMOLO_PHASE");
  public final static FMOD_DSP_TREMOLO FMOD_DSP_TREMOLO_SPREAD = new FMOD_DSP_TREMOLO("FMOD_DSP_TREMOLO_SPREAD");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_TREMOLO swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_TREMOLO.class + " with value " + swigValue);
  }

  private FMOD_DSP_TREMOLO(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_TREMOLO(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_TREMOLO(String swigName, FMOD_DSP_TREMOLO swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_TREMOLO[] swigValues = { FMOD_DSP_TREMOLO_FREQUENCY, FMOD_DSP_TREMOLO_DEPTH, FMOD_DSP_TREMOLO_SHAPE, FMOD_DSP_TREMOLO_SKEW, FMOD_DSP_TREMOLO_DUTY, FMOD_DSP_TREMOLO_SQUARE, FMOD_DSP_TREMOLO_PHASE, FMOD_DSP_TREMOLO_SPREAD };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

