package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_PAN_3D_ROLLOFF_TYPE {
  public final static FMOD_DSP_PAN_3D_ROLLOFF_TYPE FMOD_DSP_PAN_3D_ROLLOFF_LINEARSQUARED = new FMOD_DSP_PAN_3D_ROLLOFF_TYPE("FMOD_DSP_PAN_3D_ROLLOFF_LINEARSQUARED");
  public final static FMOD_DSP_PAN_3D_ROLLOFF_TYPE FMOD_DSP_PAN_3D_ROLLOFF_LINEAR = new FMOD_DSP_PAN_3D_ROLLOFF_TYPE("FMOD_DSP_PAN_3D_ROLLOFF_LINEAR");
  public final static FMOD_DSP_PAN_3D_ROLLOFF_TYPE FMOD_DSP_PAN_3D_ROLLOFF_INVERSE = new FMOD_DSP_PAN_3D_ROLLOFF_TYPE("FMOD_DSP_PAN_3D_ROLLOFF_INVERSE");
  public final static FMOD_DSP_PAN_3D_ROLLOFF_TYPE FMOD_DSP_PAN_3D_ROLLOFF_INVERSETAPERED = new FMOD_DSP_PAN_3D_ROLLOFF_TYPE("FMOD_DSP_PAN_3D_ROLLOFF_INVERSETAPERED");
  public final static FMOD_DSP_PAN_3D_ROLLOFF_TYPE FMOD_DSP_PAN_3D_ROLLOFF_CUSTOM = new FMOD_DSP_PAN_3D_ROLLOFF_TYPE("FMOD_DSP_PAN_3D_ROLLOFF_CUSTOM");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_PAN_3D_ROLLOFF_TYPE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_PAN_3D_ROLLOFF_TYPE.class + " with value " + swigValue);
  }

  private FMOD_DSP_PAN_3D_ROLLOFF_TYPE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_PAN_3D_ROLLOFF_TYPE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_PAN_3D_ROLLOFF_TYPE(String swigName, FMOD_DSP_PAN_3D_ROLLOFF_TYPE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_PAN_3D_ROLLOFF_TYPE[] swigValues = { FMOD_DSP_PAN_3D_ROLLOFF_LINEARSQUARED, FMOD_DSP_PAN_3D_ROLLOFF_LINEAR, FMOD_DSP_PAN_3D_ROLLOFF_INVERSE, FMOD_DSP_PAN_3D_ROLLOFF_INVERSETAPERED, FMOD_DSP_PAN_3D_ROLLOFF_CUSTOM };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

