package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_ERRORCALLBACK_INFO {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_ERRORCALLBACK_INFO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_ERRORCALLBACK_INFO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_ERRORCALLBACK_INFO obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_ERRORCALLBACK_INFO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setResult(FMOD_RESULT value) {
    FMODStudioJNI.FMOD_ERRORCALLBACK_INFO_result_set(swigCPtr, this, value.swigValue());
  }

  public FMOD_RESULT getResult() {
    return FMOD_RESULT.swigToEnum(FMODStudioJNI.FMOD_ERRORCALLBACK_INFO_result_get(swigCPtr, this));
  }

  public void setInstancetype(FMOD_ERRORCALLBACK_INSTANCETYPE value) {
    FMODStudioJNI.FMOD_ERRORCALLBACK_INFO_instancetype_set(swigCPtr, this, value.swigValue());
  }

  public FMOD_ERRORCALLBACK_INSTANCETYPE getInstancetype() {
    return FMOD_ERRORCALLBACK_INSTANCETYPE.swigToEnum(FMODStudioJNI.FMOD_ERRORCALLBACK_INFO_instancetype_get(swigCPtr, this));
  }

  public void setInstance(SWIGTYPE_p_void value) {
    FMODStudioJNI.FMOD_ERRORCALLBACK_INFO_instance_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getInstance() {
    long cPtr = FMODStudioJNI.FMOD_ERRORCALLBACK_INFO_instance_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setFunctionname(String value) {
    FMODStudioJNI.FMOD_ERRORCALLBACK_INFO_functionname_set(swigCPtr, this, value);
  }

  public String getFunctionname() {
    return FMODStudioJNI.FMOD_ERRORCALLBACK_INFO_functionname_get(swigCPtr, this);
  }

  public void setFunctionparams(String value) {
    FMODStudioJNI.FMOD_ERRORCALLBACK_INFO_functionparams_set(swigCPtr, this, value);
  }

  public String getFunctionparams() {
    return FMODStudioJNI.FMOD_ERRORCALLBACK_INFO_functionparams_get(swigCPtr, this);
  }

  public FMOD_ERRORCALLBACK_INFO() {
    this(FMODStudioJNI.new_FMOD_ERRORCALLBACK_INFO(), true);
  }

}
