package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_HIGHPASS {
  public final static FMOD_DSP_HIGHPASS FMOD_DSP_HIGHPASS_CUTOFF = new FMOD_DSP_HIGHPASS("FMOD_DSP_HIGHPASS_CUTOFF");
  public final static FMOD_DSP_HIGHPASS FMOD_DSP_HIGHPASS_RESONANCE = new FMOD_DSP_HIGHPASS("FMOD_DSP_HIGHPASS_RESONANCE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_HIGHPASS swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_HIGHPASS.class + " with value " + swigValue);
  }

  private FMOD_DSP_HIGHPASS(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_HIGHPASS(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_HIGHPASS(String swigName, FMOD_DSP_HIGHPASS swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_HIGHPASS[] swigValues = { FMOD_DSP_HIGHPASS_CUTOFF, FMOD_DSP_HIGHPASS_RESONANCE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

