package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_STUDIO_COMMAND_INFO {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_STUDIO_COMMAND_INFO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_STUDIO_COMMAND_INFO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_STUDIO_COMMAND_INFO obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_STUDIO_COMMAND_INFO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCommandname(String value) {
    FMODStudioJNI.FMOD_STUDIO_COMMAND_INFO_commandname_set(swigCPtr, this, value);
  }

  public String getCommandname() {
    return FMODStudioJNI.FMOD_STUDIO_COMMAND_INFO_commandname_get(swigCPtr, this);
  }

  public void setParentcommandindex(int value) {
    FMODStudioJNI.FMOD_STUDIO_COMMAND_INFO_parentcommandindex_set(swigCPtr, this, value);
  }

  public int getParentcommandindex() {
    return FMODStudioJNI.FMOD_STUDIO_COMMAND_INFO_parentcommandindex_get(swigCPtr, this);
  }

  public void setFramenumber(int value) {
    FMODStudioJNI.FMOD_STUDIO_COMMAND_INFO_framenumber_set(swigCPtr, this, value);
  }

  public int getFramenumber() {
    return FMODStudioJNI.FMOD_STUDIO_COMMAND_INFO_framenumber_get(swigCPtr, this);
  }

  public void setFrametime(float value) {
    FMODStudioJNI.FMOD_STUDIO_COMMAND_INFO_frametime_set(swigCPtr, this, value);
  }

  public float getFrametime() {
    return FMODStudioJNI.FMOD_STUDIO_COMMAND_INFO_frametime_get(swigCPtr, this);
  }

  public void setInstancetype(FMOD_STUDIO_INSTANCETYPE value) {
    FMODStudioJNI.FMOD_STUDIO_COMMAND_INFO_instancetype_set(swigCPtr, this, value.swigValue());
  }

  public FMOD_STUDIO_INSTANCETYPE getInstancetype() {
    return FMOD_STUDIO_INSTANCETYPE.swigToEnum(FMODStudioJNI.FMOD_STUDIO_COMMAND_INFO_instancetype_get(swigCPtr, this));
  }

  public void setOutputtype(FMOD_STUDIO_INSTANCETYPE value) {
    FMODStudioJNI.FMOD_STUDIO_COMMAND_INFO_outputtype_set(swigCPtr, this, value.swigValue());
  }

  public FMOD_STUDIO_INSTANCETYPE getOutputtype() {
    return FMOD_STUDIO_INSTANCETYPE.swigToEnum(FMODStudioJNI.FMOD_STUDIO_COMMAND_INFO_outputtype_get(swigCPtr, this));
  }

  public void setInstancehandle(long value) {
    FMODStudioJNI.FMOD_STUDIO_COMMAND_INFO_instancehandle_set(swigCPtr, this, value);
  }

  public long getInstancehandle() {
    return FMODStudioJNI.FMOD_STUDIO_COMMAND_INFO_instancehandle_get(swigCPtr, this);
  }

  public void setOutputhandle(long value) {
    FMODStudioJNI.FMOD_STUDIO_COMMAND_INFO_outputhandle_set(swigCPtr, this, value);
  }

  public long getOutputhandle() {
    return FMODStudioJNI.FMOD_STUDIO_COMMAND_INFO_outputhandle_get(swigCPtr, this);
  }

  public FMOD_STUDIO_COMMAND_INFO() {
    this(FMODStudioJNI.new_FMOD_STUDIO_COMMAND_INFO(), true);
  }

}
