package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_DSP_DESCRIPTION {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_DSP_DESCRIPTION(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_DSP_DESCRIPTION obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_DSP_DESCRIPTION obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_DSP_DESCRIPTION(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPluginsdkversion(long value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_pluginsdkversion_set(swigCPtr, this, value);
  }

  public long getPluginsdkversion() {
    return FMODStudioJNI.FMOD_DSP_DESCRIPTION_pluginsdkversion_get(swigCPtr, this);
  }

  public void setName(String value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return FMODStudioJNI.FMOD_DSP_DESCRIPTION_name_get(swigCPtr, this);
  }

  public void setVersion(long value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_version_set(swigCPtr, this, value);
  }

  public long getVersion() {
    return FMODStudioJNI.FMOD_DSP_DESCRIPTION_version_get(swigCPtr, this);
  }

  public void setNuminputbuffers(int value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_numinputbuffers_set(swigCPtr, this, value);
  }

  public int getNuminputbuffers() {
    return FMODStudioJNI.FMOD_DSP_DESCRIPTION_numinputbuffers_get(swigCPtr, this);
  }

  public void setNumoutputbuffers(int value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_numoutputbuffers_set(swigCPtr, this, value);
  }

  public int getNumoutputbuffers() {
    return FMODStudioJNI.FMOD_DSP_DESCRIPTION_numoutputbuffers_get(swigCPtr, this);
  }

  public void setCreate(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_create_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE__FMOD_RESULT getCreate() {
    long cPtr = FMODStudioJNI.FMOD_DSP_DESCRIPTION_create_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE__FMOD_RESULT(cPtr, false);
  }

  public void setRelease(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_release_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE__FMOD_RESULT getRelease() {
    long cPtr = FMODStudioJNI.FMOD_DSP_DESCRIPTION_release_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE__FMOD_RESULT(cPtr, false);
  }

  public void setReset(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_reset_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE__FMOD_RESULT getReset() {
    long cPtr = FMODStudioJNI.FMOD_DSP_DESCRIPTION_reset_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE__FMOD_RESULT(cPtr, false);
  }

  public void setRead(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_p_float_p_float_unsigned_int_int_p_int__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_read_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_p_float_p_float_unsigned_int_int_p_int__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_p_float_p_float_unsigned_int_int_p_int__FMOD_RESULT getRead() {
    long cPtr = FMODStudioJNI.FMOD_DSP_DESCRIPTION_read_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_p_float_p_float_unsigned_int_int_p_int__FMOD_RESULT(cPtr, false);
  }

  public void setProcess(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_unsigned_int_p_q_const__struct_FMOD_DSP_BUFFER_ARRAY_p_struct_FMOD_DSP_BUFFER_ARRAY_int_enum_FMOD_DSP_PROCESS_OPERATION__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_process_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_unsigned_int_p_q_const__struct_FMOD_DSP_BUFFER_ARRAY_p_struct_FMOD_DSP_BUFFER_ARRAY_int_enum_FMOD_DSP_PROCESS_OPERATION__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_unsigned_int_p_q_const__struct_FMOD_DSP_BUFFER_ARRAY_p_struct_FMOD_DSP_BUFFER_ARRAY_int_enum_FMOD_DSP_PROCESS_OPERATION__FMOD_RESULT getProcess() {
    long cPtr = FMODStudioJNI.FMOD_DSP_DESCRIPTION_process_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_unsigned_int_p_q_const__struct_FMOD_DSP_BUFFER_ARRAY_p_struct_FMOD_DSP_BUFFER_ARRAY_int_enum_FMOD_DSP_PROCESS_OPERATION__FMOD_RESULT(cPtr, false);
  }

  public void setSetposition(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_unsigned_int__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_setposition_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_unsigned_int__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_unsigned_int__FMOD_RESULT getSetposition() {
    long cPtr = FMODStudioJNI.FMOD_DSP_DESCRIPTION_setposition_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_unsigned_int__FMOD_RESULT(cPtr, false);
  }

  public void setNumparameters(int value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_numparameters_set(swigCPtr, this, value);
  }

  public int getNumparameters() {
    return FMODStudioJNI.FMOD_DSP_DESCRIPTION_numparameters_get(swigCPtr, this);
  }

  public void setParamdesc(SWIGTYPE_p_p_FMOD_DSP_PARAMETER_DESC value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_paramdesc_set(swigCPtr, this, SWIGTYPE_p_p_FMOD_DSP_PARAMETER_DESC.getCPtr(value));
  }

  public SWIGTYPE_p_p_FMOD_DSP_PARAMETER_DESC getParamdesc() {
    long cPtr = FMODStudioJNI.FMOD_DSP_DESCRIPTION_paramdesc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_FMOD_DSP_PARAMETER_DESC(cPtr, false);
  }

  public void setSetparameterfloat(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_float__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_setparameterfloat_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_float__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_float__FMOD_RESULT getSetparameterfloat() {
    long cPtr = FMODStudioJNI.FMOD_DSP_DESCRIPTION_setparameterfloat_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_float__FMOD_RESULT(cPtr, false);
  }

  public void setSetparameterint(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_int__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_setparameterint_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_int__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_int__FMOD_RESULT getSetparameterint() {
    long cPtr = FMODStudioJNI.FMOD_DSP_DESCRIPTION_setparameterint_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_int__FMOD_RESULT(cPtr, false);
  }

  public void setSetparameterbool(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_int__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_setparameterbool_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_int__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_int__FMOD_RESULT getSetparameterbool() {
    long cPtr = FMODStudioJNI.FMOD_DSP_DESCRIPTION_setparameterbool_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_int__FMOD_RESULT(cPtr, false);
  }

  public void setSetparameterdata(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_void_unsigned_int__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_setparameterdata_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_void_unsigned_int__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_void_unsigned_int__FMOD_RESULT getSetparameterdata() {
    long cPtr = FMODStudioJNI.FMOD_DSP_DESCRIPTION_setparameterdata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_void_unsigned_int__FMOD_RESULT(cPtr, false);
  }

  public void setGetparameterfloat(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_float_p_char__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_getparameterfloat_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_float_p_char__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_float_p_char__FMOD_RESULT getGetparameterfloat() {
    long cPtr = FMODStudioJNI.FMOD_DSP_DESCRIPTION_getparameterfloat_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_float_p_char__FMOD_RESULT(cPtr, false);
  }

  public void setGetparameterint(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_int_p_char__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_getparameterint_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_int_p_char__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_int_p_char__FMOD_RESULT getGetparameterint() {
    long cPtr = FMODStudioJNI.FMOD_DSP_DESCRIPTION_getparameterint_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_int_p_char__FMOD_RESULT(cPtr, false);
  }

  public void setGetparameterbool(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_int_p_char__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_getparameterbool_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_int_p_char__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_int_p_char__FMOD_RESULT getGetparameterbool() {
    long cPtr = FMODStudioJNI.FMOD_DSP_DESCRIPTION_getparameterbool_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_int_p_char__FMOD_RESULT(cPtr, false);
  }

  public void setGetparameterdata(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_p_void_p_unsigned_int_p_char__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_getparameterdata_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_p_void_p_unsigned_int_p_char__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_p_void_p_unsigned_int_p_char__FMOD_RESULT getGetparameterdata() {
    long cPtr = FMODStudioJNI.FMOD_DSP_DESCRIPTION_getparameterdata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_p_void_p_unsigned_int_p_char__FMOD_RESULT(cPtr, false);
  }

  public void setShouldiprocess(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_unsigned_int_unsigned_int_int_enum_FMOD_SPEAKERMODE__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_shouldiprocess_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_unsigned_int_unsigned_int_int_enum_FMOD_SPEAKERMODE__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_unsigned_int_unsigned_int_int_enum_FMOD_SPEAKERMODE__FMOD_RESULT getShouldiprocess() {
    long cPtr = FMODStudioJNI.FMOD_DSP_DESCRIPTION_shouldiprocess_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_unsigned_int_unsigned_int_int_enum_FMOD_SPEAKERMODE__FMOD_RESULT(cPtr, false);
  }

  public void setUserdata(SWIGTYPE_p_void value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_userdata_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUserdata() {
    long cPtr = FMODStudioJNI.FMOD_DSP_DESCRIPTION_userdata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setSys_register(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_sys_register_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE__FMOD_RESULT getSys_register() {
    long cPtr = FMODStudioJNI.FMOD_DSP_DESCRIPTION_sys_register_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE__FMOD_RESULT(cPtr, false);
  }

  public void setSys_deregister(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_sys_deregister_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE__FMOD_RESULT getSys_deregister() {
    long cPtr = FMODStudioJNI.FMOD_DSP_DESCRIPTION_sys_deregister_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE__FMOD_RESULT(cPtr, false);
  }

  public void setSys_mix(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_DESCRIPTION_sys_mix_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int__FMOD_RESULT getSys_mix() {
    long cPtr = FMODStudioJNI.FMOD_DSP_DESCRIPTION_sys_mix_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int__FMOD_RESULT(cPtr, false);
  }

  public FMOD_DSP_DESCRIPTION() {
    this(FMODStudioJNI.new_FMOD_DSP_DESCRIPTION(), true);
  }

}
