package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_PLUGINLIST {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_PLUGINLIST(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_PLUGINLIST obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_PLUGINLIST obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_PLUGINLIST(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(FMOD_PLUGINTYPE value) {
    FMODStudioJNI.FMOD_PLUGINLIST_type_set(swigCPtr, this, value.swigValue());
  }

  public FMOD_PLUGINTYPE getType() {
    return FMOD_PLUGINTYPE.swigToEnum(FMODStudioJNI.FMOD_PLUGINLIST_type_get(swigCPtr, this));
  }

  public void setDescription(SWIGTYPE_p_void value) {
    FMODStudioJNI.FMOD_PLUGINLIST_description_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getDescription() {
    long cPtr = FMODStudioJNI.FMOD_PLUGINLIST_description_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public FMOD_PLUGINLIST() {
    this(FMODStudioJNI.new_FMOD_PLUGINLIST(), true);
  }

}
