package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_STUDIO_ADVANCEDSETTINGS {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_STUDIO_ADVANCEDSETTINGS(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_STUDIO_ADVANCEDSETTINGS obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_STUDIO_ADVANCEDSETTINGS obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_STUDIO_ADVANCEDSETTINGS(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCbsize(int value) {
    FMODStudioJNI.FMOD_STUDIO_ADVANCEDSETTINGS_cbsize_set(swigCPtr, this, value);
  }

  public int getCbsize() {
    return FMODStudioJNI.FMOD_STUDIO_ADVANCEDSETTINGS_cbsize_get(swigCPtr, this);
  }

  public void setCommandqueuesize(long value) {
    FMODStudioJNI.FMOD_STUDIO_ADVANCEDSETTINGS_commandqueuesize_set(swigCPtr, this, value);
  }

  public long getCommandqueuesize() {
    return FMODStudioJNI.FMOD_STUDIO_ADVANCEDSETTINGS_commandqueuesize_get(swigCPtr, this);
  }

  public void setHandleinitialsize(long value) {
    FMODStudioJNI.FMOD_STUDIO_ADVANCEDSETTINGS_handleinitialsize_set(swigCPtr, this, value);
  }

  public long getHandleinitialsize() {
    return FMODStudioJNI.FMOD_STUDIO_ADVANCEDSETTINGS_handleinitialsize_get(swigCPtr, this);
  }

  public void setStudioupdateperiod(int value) {
    FMODStudioJNI.FMOD_STUDIO_ADVANCEDSETTINGS_studioupdateperiod_set(swigCPtr, this, value);
  }

  public int getStudioupdateperiod() {
    return FMODStudioJNI.FMOD_STUDIO_ADVANCEDSETTINGS_studioupdateperiod_get(swigCPtr, this);
  }

  public void setIdlesampledatapoolsize(int value) {
    FMODStudioJNI.FMOD_STUDIO_ADVANCEDSETTINGS_idlesampledatapoolsize_set(swigCPtr, this, value);
  }

  public int getIdlesampledatapoolsize() {
    return FMODStudioJNI.FMOD_STUDIO_ADVANCEDSETTINGS_idlesampledatapoolsize_get(swigCPtr, this);
  }

  public void setStreamingscheduledelay(long value) {
    FMODStudioJNI.FMOD_STUDIO_ADVANCEDSETTINGS_streamingscheduledelay_set(swigCPtr, this, value);
  }

  public long getStreamingscheduledelay() {
    return FMODStudioJNI.FMOD_STUDIO_ADVANCEDSETTINGS_streamingscheduledelay_get(swigCPtr, this);
  }

  public void setEncryptionkey(String value) {
    FMODStudioJNI.FMOD_STUDIO_ADVANCEDSETTINGS_encryptionkey_set(swigCPtr, this, value);
  }

  public String getEncryptionkey() {
    return FMODStudioJNI.FMOD_STUDIO_ADVANCEDSETTINGS_encryptionkey_get(swigCPtr, this);
  }

  public FMOD_STUDIO_ADVANCEDSETTINGS() {
    this(FMODStudioJNI.new_FMOD_STUDIO_ADVANCEDSETTINGS(), true);
  }

}
