package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_TAG {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_TAG(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_TAG obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_TAG obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_TAG(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(FMOD_TAGTYPE value) {
    FMODStudioJNI.FMOD_TAG_type_set(swigCPtr, this, value.swigValue());
  }

  public FMOD_TAGTYPE getType() {
    return FMOD_TAGTYPE.swigToEnum(FMODStudioJNI.FMOD_TAG_type_get(swigCPtr, this));
  }

  public void setDatatype(FMOD_TAGDATATYPE value) {
    FMODStudioJNI.FMOD_TAG_datatype_set(swigCPtr, this, value.swigValue());
  }

  public FMOD_TAGDATATYPE getDatatype() {
    return FMOD_TAGDATATYPE.swigToEnum(FMODStudioJNI.FMOD_TAG_datatype_get(swigCPtr, this));
  }

  public void setName(String value) {
    FMODStudioJNI.FMOD_TAG_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return FMODStudioJNI.FMOD_TAG_name_get(swigCPtr, this);
  }

  public void setData(SWIGTYPE_p_void value) {
    FMODStudioJNI.FMOD_TAG_data_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getData() {
    long cPtr = FMODStudioJNI.FMOD_TAG_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setDatalen(long value) {
    FMODStudioJNI.FMOD_TAG_datalen_set(swigCPtr, this, value);
  }

  public long getDatalen() {
    return FMODStudioJNI.FMOD_TAG_datalen_get(swigCPtr, this);
  }

  public void setUpdated(int value) {
    FMODStudioJNI.FMOD_TAG_updated_set(swigCPtr, this, value);
  }

  public int getUpdated() {
    return FMODStudioJNI.FMOD_TAG_updated_get(swigCPtr, this);
  }

  public FMOD_TAG() {
    this(FMODStudioJNI.new_FMOD_TAG(), true);
  }

}
