package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_PITCHSHIFT {
  public final static FMOD_DSP_PITCHSHIFT FMOD_DSP_PITCHSHIFT_PITCH = new FMOD_DSP_PITCHSHIFT("FMOD_DSP_PITCHSHIFT_PITCH");
  public final static FMOD_DSP_PITCHSHIFT FMOD_DSP_PITCHSHIFT_FFTSIZE = new FMOD_DSP_PITCHSHIFT("FMOD_DSP_PITCHSHIFT_FFTSIZE");
  public final static FMOD_DSP_PITCHSHIFT FMOD_DSP_PITCHSHIFT_OVERLAP = new FMOD_DSP_PITCHSHIFT("FMOD_DSP_PITCHSHIFT_OVERLAP");
  public final static FMOD_DSP_PITCHSHIFT FMOD_DSP_PITCHSHIFT_MAXCHANNELS = new FMOD_DSP_PITCHSHIFT("FMOD_DSP_PITCHSHIFT_MAXCHANNELS");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_PITCHSHIFT swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_PITCHSHIFT.class + " with value " + swigValue);
  }

  private FMOD_DSP_PITCHSHIFT(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_PITCHSHIFT(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_PITCHSHIFT(String swigName, FMOD_DSP_PITCHSHIFT swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_PITCHSHIFT[] swigValues = { FMOD_DSP_PITCHSHIFT_PITCH, FMOD_DSP_PITCHSHIFT_FFTSIZE, FMOD_DSP_PITCHSHIFT_OVERLAP, FMOD_DSP_PITCHSHIFT_MAXCHANNELS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

