package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_CHANNELCONTROL_DSP_INDEX {
  public final static FMOD_CHANNELCONTROL_DSP_INDEX FMOD_CHANNELCONTROL_DSP_HEAD = new FMOD_CHANNELCONTROL_DSP_INDEX("FMOD_CHANNELCONTROL_DSP_HEAD", FMODStudioJNI.FMOD_CHANNELCONTROL_DSP_HEAD_get());
  public final static FMOD_CHANNELCONTROL_DSP_INDEX FMOD_CHANNELCONTROL_DSP_FADER = new FMOD_CHANNELCONTROL_DSP_INDEX("FMOD_CHANNELCONTROL_DSP_FADER", FMODStudioJNI.FMOD_CHANNELCONTROL_DSP_FADER_get());
  public final static FMOD_CHANNELCONTROL_DSP_INDEX FMOD_CHANNELCONTROL_DSP_TAIL = new FMOD_CHANNELCONTROL_DSP_INDEX("FMOD_CHANNELCONTROL_DSP_TAIL", FMODStudioJNI.FMOD_CHANNELCONTROL_DSP_TAIL_get());
  public final static FMOD_CHANNELCONTROL_DSP_INDEX FMOD_CHANNELCONTROL_DSP_FORCEINT = new FMOD_CHANNELCONTROL_DSP_INDEX("FMOD_CHANNELCONTROL_DSP_FORCEINT", FMODStudioJNI.FMOD_CHANNELCONTROL_DSP_FORCEINT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_CHANNELCONTROL_DSP_INDEX swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_CHANNELCONTROL_DSP_INDEX.class + " with value " + swigValue);
  }

  private FMOD_CHANNELCONTROL_DSP_INDEX(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_CHANNELCONTROL_DSP_INDEX(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_CHANNELCONTROL_DSP_INDEX(String swigName, FMOD_CHANNELCONTROL_DSP_INDEX swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_CHANNELCONTROL_DSP_INDEX[] swigValues = { FMOD_CHANNELCONTROL_DSP_HEAD, FMOD_CHANNELCONTROL_DSP_FADER, FMOD_CHANNELCONTROL_DSP_TAIL, FMOD_CHANNELCONTROL_DSP_FORCEINT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

