package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_CODEC_STATE_FUNCTIONS {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_CODEC_STATE_FUNCTIONS(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_CODEC_STATE_FUNCTIONS obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_CODEC_STATE_FUNCTIONS obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_CODEC_STATE_FUNCTIONS(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMetadata(SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_enum_FMOD_TAGTYPE_p_char_p_void_unsigned_int_enum_FMOD_TAGDATATYPE_int__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_CODEC_STATE_FUNCTIONS_metadata_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_enum_FMOD_TAGTYPE_p_char_p_void_unsigned_int_enum_FMOD_TAGDATATYPE_int__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_enum_FMOD_TAGTYPE_p_char_p_void_unsigned_int_enum_FMOD_TAGDATATYPE_int__FMOD_RESULT getMetadata() {
    long cPtr = FMODStudioJNI.FMOD_CODEC_STATE_FUNCTIONS_metadata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_enum_FMOD_TAGTYPE_p_char_p_void_unsigned_int_enum_FMOD_TAGDATATYPE_int__FMOD_RESULT(cPtr, false);
  }

  public void setAlloc(SWIGTYPE_p_f_unsigned_int_unsigned_int_p_q_const__char_int__p_void value) {
    FMODStudioJNI.FMOD_CODEC_STATE_FUNCTIONS_alloc_set(swigCPtr, this, SWIGTYPE_p_f_unsigned_int_unsigned_int_p_q_const__char_int__p_void.getCPtr(value));
  }

  public SWIGTYPE_p_f_unsigned_int_unsigned_int_p_q_const__char_int__p_void getAlloc() {
    long cPtr = FMODStudioJNI.FMOD_CODEC_STATE_FUNCTIONS_alloc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_unsigned_int_unsigned_int_p_q_const__char_int__p_void(cPtr, false);
  }

  public void setFree(SWIGTYPE_p_f_p_void_p_q_const__char_int__void value) {
    FMODStudioJNI.FMOD_CODEC_STATE_FUNCTIONS_free_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_q_const__char_int__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_q_const__char_int__void getFree() {
    long cPtr = FMODStudioJNI.FMOD_CODEC_STATE_FUNCTIONS_free_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_q_const__char_int__void(cPtr, false);
  }

  public void setLog(SWIGTYPE_p_f_unsigned_int_p_q_const__char_int_p_q_const__char_p_q_const__char_v_______void value) {
    FMODStudioJNI.FMOD_CODEC_STATE_FUNCTIONS_log_set(swigCPtr, this, SWIGTYPE_p_f_unsigned_int_p_q_const__char_int_p_q_const__char_p_q_const__char_v_______void.getCPtr(value));
  }

  public SWIGTYPE_p_f_unsigned_int_p_q_const__char_int_p_q_const__char_p_q_const__char_v_______void getLog() {
    long cPtr = FMODStudioJNI.FMOD_CODEC_STATE_FUNCTIONS_log_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_unsigned_int_p_q_const__char_int_p_q_const__char_p_q_const__char_v_______void(cPtr, false);
  }

  public void setRead(SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_p_void_unsigned_int_p_unsigned_int__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_CODEC_STATE_FUNCTIONS_read_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_p_void_unsigned_int_p_unsigned_int__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_p_void_unsigned_int_p_unsigned_int__FMOD_RESULT getRead() {
    long cPtr = FMODStudioJNI.FMOD_CODEC_STATE_FUNCTIONS_read_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_p_void_unsigned_int_p_unsigned_int__FMOD_RESULT(cPtr, false);
  }

  public void setSeek(SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_unsigned_int_int__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_CODEC_STATE_FUNCTIONS_seek_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_unsigned_int_int__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_unsigned_int_int__FMOD_RESULT getSeek() {
    long cPtr = FMODStudioJNI.FMOD_CODEC_STATE_FUNCTIONS_seek_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_unsigned_int_int__FMOD_RESULT(cPtr, false);
  }

  public void setTell(SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_p_unsigned_int__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_CODEC_STATE_FUNCTIONS_tell_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_p_unsigned_int__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_p_unsigned_int__FMOD_RESULT getTell() {
    long cPtr = FMODStudioJNI.FMOD_CODEC_STATE_FUNCTIONS_tell_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_p_unsigned_int__FMOD_RESULT(cPtr, false);
  }

  public void setSize(SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_p_unsigned_int__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_CODEC_STATE_FUNCTIONS_size_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_p_unsigned_int__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_p_unsigned_int__FMOD_RESULT getSize() {
    long cPtr = FMODStudioJNI.FMOD_CODEC_STATE_FUNCTIONS_size_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_p_unsigned_int__FMOD_RESULT(cPtr, false);
  }

  public FMOD_CODEC_STATE_FUNCTIONS() {
    this(FMODStudioJNI.new_FMOD_CODEC_STATE_FUNCTIONS(), true);
  }

}
