package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_VECTOR {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_VECTOR(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_VECTOR obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_VECTOR obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_VECTOR(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(float value) {
    FMODStudioJNI.FMOD_VECTOR_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return FMODStudioJNI.FMOD_VECTOR_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    FMODStudioJNI.FMOD_VECTOR_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return FMODStudioJNI.FMOD_VECTOR_y_get(swigCPtr, this);
  }

  public void setZ(float value) {
    FMODStudioJNI.FMOD_VECTOR_z_set(swigCPtr, this, value);
  }

  public float getZ() {
    return FMODStudioJNI.FMOD_VECTOR_z_get(swigCPtr, this);
  }

  public FMOD_VECTOR() {
    this(FMODStudioJNI.new_FMOD_VECTOR(), true);
  }

}
