package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_ASYNCREADINFO {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_ASYNCREADINFO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_ASYNCREADINFO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_ASYNCREADINFO obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_ASYNCREADINFO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHandle(SWIGTYPE_p_void value) {
    FMODStudioJNI.FMOD_ASYNCREADINFO_handle_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getHandle() {
    long cPtr = FMODStudioJNI.FMOD_ASYNCREADINFO_handle_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setOffset(long value) {
    FMODStudioJNI.FMOD_ASYNCREADINFO_offset_set(swigCPtr, this, value);
  }

  public long getOffset() {
    return FMODStudioJNI.FMOD_ASYNCREADINFO_offset_get(swigCPtr, this);
  }

  public void setSizebytes(long value) {
    FMODStudioJNI.FMOD_ASYNCREADINFO_sizebytes_set(swigCPtr, this, value);
  }

  public long getSizebytes() {
    return FMODStudioJNI.FMOD_ASYNCREADINFO_sizebytes_get(swigCPtr, this);
  }

  public void setPriority(int value) {
    FMODStudioJNI.FMOD_ASYNCREADINFO_priority_set(swigCPtr, this, value);
  }

  public int getPriority() {
    return FMODStudioJNI.FMOD_ASYNCREADINFO_priority_get(swigCPtr, this);
  }

  public void setUserdata(SWIGTYPE_p_void value) {
    FMODStudioJNI.FMOD_ASYNCREADINFO_userdata_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUserdata() {
    long cPtr = FMODStudioJNI.FMOD_ASYNCREADINFO_userdata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setBuffer(SWIGTYPE_p_void value) {
    FMODStudioJNI.FMOD_ASYNCREADINFO_buffer_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getBuffer() {
    long cPtr = FMODStudioJNI.FMOD_ASYNCREADINFO_buffer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setBytesread(long value) {
    FMODStudioJNI.FMOD_ASYNCREADINFO_bytesread_set(swigCPtr, this, value);
  }

  public long getBytesread() {
    return FMODStudioJNI.FMOD_ASYNCREADINFO_bytesread_get(swigCPtr, this);
  }

  public void setDone(SWIGTYPE_p_f_p_struct_FMOD_ASYNCREADINFO_enum_FMOD_RESULT__void value) {
    FMODStudioJNI.FMOD_ASYNCREADINFO_done_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_ASYNCREADINFO_enum_FMOD_RESULT__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_ASYNCREADINFO_enum_FMOD_RESULT__void getDone() {
    long cPtr = FMODStudioJNI.FMOD_ASYNCREADINFO_done_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_ASYNCREADINFO_enum_FMOD_RESULT__void(cPtr, false);
  }

  public FMOD_ASYNCREADINFO() {
    this(FMODStudioJNI.new_FMOD_ASYNCREADINFO(), true);
  }

}
