package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_STUDIO_BANK_INFO {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_STUDIO_BANK_INFO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_STUDIO_BANK_INFO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_STUDIO_BANK_INFO obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_STUDIO_BANK_INFO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSize(int value) {
    FMODStudioJNI.FMOD_STUDIO_BANK_INFO_size_set(swigCPtr, this, value);
  }

  public int getSize() {
    return FMODStudioJNI.FMOD_STUDIO_BANK_INFO_size_get(swigCPtr, this);
  }

  public void setUserdata(SWIGTYPE_p_void value) {
    FMODStudioJNI.FMOD_STUDIO_BANK_INFO_userdata_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUserdata() {
    long cPtr = FMODStudioJNI.FMOD_STUDIO_BANK_INFO_userdata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setUserdatalength(int value) {
    FMODStudioJNI.FMOD_STUDIO_BANK_INFO_userdatalength_set(swigCPtr, this, value);
  }

  public int getUserdatalength() {
    return FMODStudioJNI.FMOD_STUDIO_BANK_INFO_userdatalength_get(swigCPtr, this);
  }

  public void setOpencallback(SWIGTYPE_p_f_p_q_const__char_p_unsigned_int_p_p_void_p_void__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_STUDIO_BANK_INFO_opencallback_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__char_p_unsigned_int_p_p_void_p_void__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__char_p_unsigned_int_p_p_void_p_void__FMOD_RESULT getOpencallback() {
    long cPtr = FMODStudioJNI.FMOD_STUDIO_BANK_INFO_opencallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__char_p_unsigned_int_p_p_void_p_void__FMOD_RESULT(cPtr, false);
  }

  public void setClosecallback(SWIGTYPE_p_f_p_void_p_void__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_STUDIO_BANK_INFO_closecallback_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_void__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_void__FMOD_RESULT getClosecallback() {
    long cPtr = FMODStudioJNI.FMOD_STUDIO_BANK_INFO_closecallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_void__FMOD_RESULT(cPtr, false);
  }

  public void setReadcallback(SWIGTYPE_p_f_p_void_p_void_unsigned_int_p_unsigned_int_p_void__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_STUDIO_BANK_INFO_readcallback_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_void_unsigned_int_p_unsigned_int_p_void__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_void_unsigned_int_p_unsigned_int_p_void__FMOD_RESULT getReadcallback() {
    long cPtr = FMODStudioJNI.FMOD_STUDIO_BANK_INFO_readcallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_void_unsigned_int_p_unsigned_int_p_void__FMOD_RESULT(cPtr, false);
  }

  public void setSeekcallback(SWIGTYPE_p_f_p_void_unsigned_int_p_void__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_STUDIO_BANK_INFO_seekcallback_set(swigCPtr, this, SWIGTYPE_p_f_p_void_unsigned_int_p_void__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_unsigned_int_p_void__FMOD_RESULT getSeekcallback() {
    long cPtr = FMODStudioJNI.FMOD_STUDIO_BANK_INFO_seekcallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_unsigned_int_p_void__FMOD_RESULT(cPtr, false);
  }

  public FMOD_STUDIO_BANK_INFO() {
    this(FMODStudioJNI.new_FMOD_STUDIO_BANK_INFO(), true);
  }

}
