package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_DELAY {
  public final static FMOD_DSP_DELAY FMOD_DSP_DELAY_CH0 = new FMOD_DSP_DELAY("FMOD_DSP_DELAY_CH0");
  public final static FMOD_DSP_DELAY FMOD_DSP_DELAY_CH1 = new FMOD_DSP_DELAY("FMOD_DSP_DELAY_CH1");
  public final static FMOD_DSP_DELAY FMOD_DSP_DELAY_CH2 = new FMOD_DSP_DELAY("FMOD_DSP_DELAY_CH2");
  public final static FMOD_DSP_DELAY FMOD_DSP_DELAY_CH3 = new FMOD_DSP_DELAY("FMOD_DSP_DELAY_CH3");
  public final static FMOD_DSP_DELAY FMOD_DSP_DELAY_CH4 = new FMOD_DSP_DELAY("FMOD_DSP_DELAY_CH4");
  public final static FMOD_DSP_DELAY FMOD_DSP_DELAY_CH5 = new FMOD_DSP_DELAY("FMOD_DSP_DELAY_CH5");
  public final static FMOD_DSP_DELAY FMOD_DSP_DELAY_CH6 = new FMOD_DSP_DELAY("FMOD_DSP_DELAY_CH6");
  public final static FMOD_DSP_DELAY FMOD_DSP_DELAY_CH7 = new FMOD_DSP_DELAY("FMOD_DSP_DELAY_CH7");
  public final static FMOD_DSP_DELAY FMOD_DSP_DELAY_CH8 = new FMOD_DSP_DELAY("FMOD_DSP_DELAY_CH8");
  public final static FMOD_DSP_DELAY FMOD_DSP_DELAY_CH9 = new FMOD_DSP_DELAY("FMOD_DSP_DELAY_CH9");
  public final static FMOD_DSP_DELAY FMOD_DSP_DELAY_CH10 = new FMOD_DSP_DELAY("FMOD_DSP_DELAY_CH10");
  public final static FMOD_DSP_DELAY FMOD_DSP_DELAY_CH11 = new FMOD_DSP_DELAY("FMOD_DSP_DELAY_CH11");
  public final static FMOD_DSP_DELAY FMOD_DSP_DELAY_CH12 = new FMOD_DSP_DELAY("FMOD_DSP_DELAY_CH12");
  public final static FMOD_DSP_DELAY FMOD_DSP_DELAY_CH13 = new FMOD_DSP_DELAY("FMOD_DSP_DELAY_CH13");
  public final static FMOD_DSP_DELAY FMOD_DSP_DELAY_CH14 = new FMOD_DSP_DELAY("FMOD_DSP_DELAY_CH14");
  public final static FMOD_DSP_DELAY FMOD_DSP_DELAY_CH15 = new FMOD_DSP_DELAY("FMOD_DSP_DELAY_CH15");
  public final static FMOD_DSP_DELAY FMOD_DSP_DELAY_MAXDELAY = new FMOD_DSP_DELAY("FMOD_DSP_DELAY_MAXDELAY");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_DELAY swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_DELAY.class + " with value " + swigValue);
  }

  private FMOD_DSP_DELAY(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_DELAY(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_DELAY(String swigName, FMOD_DSP_DELAY swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_DELAY[] swigValues = { FMOD_DSP_DELAY_CH0, FMOD_DSP_DELAY_CH1, FMOD_DSP_DELAY_CH2, FMOD_DSP_DELAY_CH3, FMOD_DSP_DELAY_CH4, FMOD_DSP_DELAY_CH5, FMOD_DSP_DELAY_CH6, FMOD_DSP_DELAY_CH7, FMOD_DSP_DELAY_CH8, FMOD_DSP_DELAY_CH9, FMOD_DSP_DELAY_CH10, FMOD_DSP_DELAY_CH11, FMOD_DSP_DELAY_CH12, FMOD_DSP_DELAY_CH13, FMOD_DSP_DELAY_CH14, FMOD_DSP_DELAY_CH15, FMOD_DSP_DELAY_MAXDELAY };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

