package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    FMODStudioJNI.FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return FMODStudioJNI.FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES_name_get(swigCPtr, this);
  }

  public void setSound(SWIGTYPE_p_FMOD_SOUND value) {
    FMODStudioJNI.FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES_sound_set(swigCPtr, this, SWIGTYPE_p_FMOD_SOUND.getCPtr(value));
  }

  public SWIGTYPE_p_FMOD_SOUND getSound() {
    long cPtr = FMODStudioJNI.FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES_sound_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FMOD_SOUND(cPtr, false);
  }

  public void setSubsoundIndex(int value) {
    FMODStudioJNI.FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES_subsoundIndex_set(swigCPtr, this, value);
  }

  public int getSubsoundIndex() {
    return FMODStudioJNI.FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES_subsoundIndex_get(swigCPtr, this);
  }

  public FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES() {
    this(FMODStudioJNI.new_FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES(), true);
  }

}
