package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_PARAMETER_DATA_TYPE {
  public final static FMOD_DSP_PARAMETER_DATA_TYPE FMOD_DSP_PARAMETER_DATA_TYPE_USER = new FMOD_DSP_PARAMETER_DATA_TYPE("FMOD_DSP_PARAMETER_DATA_TYPE_USER", FMODStudioJNI.FMOD_DSP_PARAMETER_DATA_TYPE_USER_get());
  public final static FMOD_DSP_PARAMETER_DATA_TYPE FMOD_DSP_PARAMETER_DATA_TYPE_OVERALLGAIN = new FMOD_DSP_PARAMETER_DATA_TYPE("FMOD_DSP_PARAMETER_DATA_TYPE_OVERALLGAIN", FMODStudioJNI.FMOD_DSP_PARAMETER_DATA_TYPE_OVERALLGAIN_get());
  public final static FMOD_DSP_PARAMETER_DATA_TYPE FMOD_DSP_PARAMETER_DATA_TYPE_3DATTRIBUTES = new FMOD_DSP_PARAMETER_DATA_TYPE("FMOD_DSP_PARAMETER_DATA_TYPE_3DATTRIBUTES", FMODStudioJNI.FMOD_DSP_PARAMETER_DATA_TYPE_3DATTRIBUTES_get());
  public final static FMOD_DSP_PARAMETER_DATA_TYPE FMOD_DSP_PARAMETER_DATA_TYPE_SIDECHAIN = new FMOD_DSP_PARAMETER_DATA_TYPE("FMOD_DSP_PARAMETER_DATA_TYPE_SIDECHAIN", FMODStudioJNI.FMOD_DSP_PARAMETER_DATA_TYPE_SIDECHAIN_get());
  public final static FMOD_DSP_PARAMETER_DATA_TYPE FMOD_DSP_PARAMETER_DATA_TYPE_FFT = new FMOD_DSP_PARAMETER_DATA_TYPE("FMOD_DSP_PARAMETER_DATA_TYPE_FFT", FMODStudioJNI.FMOD_DSP_PARAMETER_DATA_TYPE_FFT_get());
  public final static FMOD_DSP_PARAMETER_DATA_TYPE FMOD_DSP_PARAMETER_DATA_TYPE_3DATTRIBUTES_MULTI = new FMOD_DSP_PARAMETER_DATA_TYPE("FMOD_DSP_PARAMETER_DATA_TYPE_3DATTRIBUTES_MULTI", FMODStudioJNI.FMOD_DSP_PARAMETER_DATA_TYPE_3DATTRIBUTES_MULTI_get());
  public final static FMOD_DSP_PARAMETER_DATA_TYPE FMOD_DSP_PARAMETER_DATA_TYPE_ATTENUATION_RANGE = new FMOD_DSP_PARAMETER_DATA_TYPE("FMOD_DSP_PARAMETER_DATA_TYPE_ATTENUATION_RANGE", FMODStudioJNI.FMOD_DSP_PARAMETER_DATA_TYPE_ATTENUATION_RANGE_get());
  public final static FMOD_DSP_PARAMETER_DATA_TYPE FMOD_DSP_PARAMETER_DATA_TYPE_DYNAMIC_RESPONSE = new FMOD_DSP_PARAMETER_DATA_TYPE("FMOD_DSP_PARAMETER_DATA_TYPE_DYNAMIC_RESPONSE", FMODStudioJNI.FMOD_DSP_PARAMETER_DATA_TYPE_DYNAMIC_RESPONSE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_PARAMETER_DATA_TYPE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_PARAMETER_DATA_TYPE.class + " with value " + swigValue);
  }

  private FMOD_DSP_PARAMETER_DATA_TYPE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_PARAMETER_DATA_TYPE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_PARAMETER_DATA_TYPE(String swigName, FMOD_DSP_PARAMETER_DATA_TYPE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_PARAMETER_DATA_TYPE[] swigValues = { FMOD_DSP_PARAMETER_DATA_TYPE_USER, FMOD_DSP_PARAMETER_DATA_TYPE_OVERALLGAIN, FMOD_DSP_PARAMETER_DATA_TYPE_3DATTRIBUTES, FMOD_DSP_PARAMETER_DATA_TYPE_SIDECHAIN, FMOD_DSP_PARAMETER_DATA_TYPE_FFT, FMOD_DSP_PARAMETER_DATA_TYPE_3DATTRIBUTES_MULTI, FMOD_DSP_PARAMETER_DATA_TYPE_ATTENUATION_RANGE, FMOD_DSP_PARAMETER_DATA_TYPE_DYNAMIC_RESPONSE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

