package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEventid(FMOD_GUID value) {
    FMODStudioJNI.FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES_eventid_set(swigCPtr, this, FMOD_GUID.getCPtr(value), value);
  }

  public FMOD_GUID getEventid() {
    long cPtr = FMODStudioJNI.FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES_eventid_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_GUID(cPtr, false);
  }

  public void setProperties(FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES value) {
    FMODStudioJNI.FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES_properties_set(swigCPtr, this, FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES.getCPtr(value), value);
  }

  public FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES getProperties() {
    long cPtr = FMODStudioJNI.FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES_properties_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES(cPtr, false);
  }

  public FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES() {
    this(FMODStudioJNI.new_FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES(), true);
  }

}
