package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_GUID {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_GUID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_GUID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_GUID obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_GUID(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData1(long value) {
    FMODStudioJNI.FMOD_GUID_Data1_set(swigCPtr, this, value);
  }

  public long getData1() {
    return FMODStudioJNI.FMOD_GUID_Data1_get(swigCPtr, this);
  }

  public void setData2(int value) {
    FMODStudioJNI.FMOD_GUID_Data2_set(swigCPtr, this, value);
  }

  public int getData2() {
    return FMODStudioJNI.FMOD_GUID_Data2_get(swigCPtr, this);
  }

  public void setData3(int value) {
    FMODStudioJNI.FMOD_GUID_Data3_set(swigCPtr, this, value);
  }

  public int getData3() {
    return FMODStudioJNI.FMOD_GUID_Data3_get(swigCPtr, this);
  }

  public void setData4(SWIGTYPE_p_unsigned_char value) {
    FMODStudioJNI.FMOD_GUID_Data4_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getData4() {
    long cPtr = FMODStudioJNI.FMOD_GUID_Data4_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public FMOD_GUID() {
    this(FMODStudioJNI.new_FMOD_GUID(), true);
  }

}
