package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_TRANSCEIVER_SPEAKERMODE {
  public final static FMOD_DSP_TRANSCEIVER_SPEAKERMODE FMOD_DSP_TRANSCEIVER_SPEAKERMODE_AUTO = new FMOD_DSP_TRANSCEIVER_SPEAKERMODE("FMOD_DSP_TRANSCEIVER_SPEAKERMODE_AUTO", FMODStudioJNI.FMOD_DSP_TRANSCEIVER_SPEAKERMODE_AUTO_get());
  public final static FMOD_DSP_TRANSCEIVER_SPEAKERMODE FMOD_DSP_TRANSCEIVER_SPEAKERMODE_MONO = new FMOD_DSP_TRANSCEIVER_SPEAKERMODE("FMOD_DSP_TRANSCEIVER_SPEAKERMODE_MONO", FMODStudioJNI.FMOD_DSP_TRANSCEIVER_SPEAKERMODE_MONO_get());
  public final static FMOD_DSP_TRANSCEIVER_SPEAKERMODE FMOD_DSP_TRANSCEIVER_SPEAKERMODE_STEREO = new FMOD_DSP_TRANSCEIVER_SPEAKERMODE("FMOD_DSP_TRANSCEIVER_SPEAKERMODE_STEREO");
  public final static FMOD_DSP_TRANSCEIVER_SPEAKERMODE FMOD_DSP_TRANSCEIVER_SPEAKERMODE_SURROUND = new FMOD_DSP_TRANSCEIVER_SPEAKERMODE("FMOD_DSP_TRANSCEIVER_SPEAKERMODE_SURROUND");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_TRANSCEIVER_SPEAKERMODE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_TRANSCEIVER_SPEAKERMODE.class + " with value " + swigValue);
  }

  private FMOD_DSP_TRANSCEIVER_SPEAKERMODE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_TRANSCEIVER_SPEAKERMODE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_TRANSCEIVER_SPEAKERMODE(String swigName, FMOD_DSP_TRANSCEIVER_SPEAKERMODE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_TRANSCEIVER_SPEAKERMODE[] swigValues = { FMOD_DSP_TRANSCEIVER_SPEAKERMODE_AUTO, FMOD_DSP_TRANSCEIVER_SPEAKERMODE_MONO, FMOD_DSP_TRANSCEIVER_SPEAKERMODE_STEREO, FMOD_DSP_TRANSCEIVER_SPEAKERMODE_SURROUND };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

