package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_FFT {
  public final static FMOD_DSP_FFT FMOD_DSP_FFT_WINDOWSIZE = new FMOD_DSP_FFT("FMOD_DSP_FFT_WINDOWSIZE");
  public final static FMOD_DSP_FFT FMOD_DSP_FFT_WINDOW = new FMOD_DSP_FFT("FMOD_DSP_FFT_WINDOW");
  public final static FMOD_DSP_FFT FMOD_DSP_FFT_BAND_START_FREQ = new FMOD_DSP_FFT("FMOD_DSP_FFT_BAND_START_FREQ");
  public final static FMOD_DSP_FFT FMOD_DSP_FFT_BAND_STOP_FREQ = new FMOD_DSP_FFT("FMOD_DSP_FFT_BAND_STOP_FREQ");
  public final static FMOD_DSP_FFT FMOD_DSP_FFT_SPECTRUMDATA = new FMOD_DSP_FFT("FMOD_DSP_FFT_SPECTRUMDATA");
  public final static FMOD_DSP_FFT FMOD_DSP_FFT_RMS = new FMOD_DSP_FFT("FMOD_DSP_FFT_RMS");
  public final static FMOD_DSP_FFT FMOD_DSP_FFT_SPECTRAL_CENTROID = new FMOD_DSP_FFT("FMOD_DSP_FFT_SPECTRAL_CENTROID");
  public final static FMOD_DSP_FFT FMOD_DSP_FFT_IMMEDIATE_MODE = new FMOD_DSP_FFT("FMOD_DSP_FFT_IMMEDIATE_MODE");
  public final static FMOD_DSP_FFT FMOD_DSP_FFT_DOWNMIX = new FMOD_DSP_FFT("FMOD_DSP_FFT_DOWNMIX");
  public final static FMOD_DSP_FFT FMOD_DSP_FFT_CHANNEL = new FMOD_DSP_FFT("FMOD_DSP_FFT_CHANNEL");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_FFT swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_FFT.class + " with value " + swigValue);
  }

  private FMOD_DSP_FFT(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_FFT(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_FFT(String swigName, FMOD_DSP_FFT swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_FFT[] swigValues = { FMOD_DSP_FFT_WINDOWSIZE, FMOD_DSP_FFT_WINDOW, FMOD_DSP_FFT_BAND_START_FREQ, FMOD_DSP_FFT_BAND_STOP_FREQ, FMOD_DSP_FFT_SPECTRUMDATA, FMOD_DSP_FFT_RMS, FMOD_DSP_FFT_SPECTRAL_CENTROID, FMOD_DSP_FFT_IMMEDIATE_MODE, FMOD_DSP_FFT_DOWNMIX, FMOD_DSP_FFT_CHANNEL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

