package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_NORMALIZE {
  public final static FMOD_DSP_NORMALIZE FMOD_DSP_NORMALIZE_FADETIME = new FMOD_DSP_NORMALIZE("FMOD_DSP_NORMALIZE_FADETIME");
  public final static FMOD_DSP_NORMALIZE FMOD_DSP_NORMALIZE_THRESHOLD = new FMOD_DSP_NORMALIZE("FMOD_DSP_NORMALIZE_THRESHOLD");
  public final static FMOD_DSP_NORMALIZE FMOD_DSP_NORMALIZE_MAXAMP = new FMOD_DSP_NORMALIZE("FMOD_DSP_NORMALIZE_MAXAMP");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_NORMALIZE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_NORMALIZE.class + " with value " + swigValue);
  }

  private FMOD_DSP_NORMALIZE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_NORMALIZE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_NORMALIZE(String swigName, FMOD_DSP_NORMALIZE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_NORMALIZE[] swigValues = { FMOD_DSP_NORMALIZE_FADETIME, FMOD_DSP_NORMALIZE_THRESHOLD, FMOD_DSP_NORMALIZE_MAXAMP };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

