package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_STUDIO_PARAMETER_DESCRIPTION {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_STUDIO_PARAMETER_DESCRIPTION(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_STUDIO_PARAMETER_DESCRIPTION obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_STUDIO_PARAMETER_DESCRIPTION obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_STUDIO_PARAMETER_DESCRIPTION(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    FMODStudioJNI.FMOD_STUDIO_PARAMETER_DESCRIPTION_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return FMODStudioJNI.FMOD_STUDIO_PARAMETER_DESCRIPTION_name_get(swigCPtr, this);
  }

  public void setId(FMOD_STUDIO_PARAMETER_ID value) {
    FMODStudioJNI.FMOD_STUDIO_PARAMETER_DESCRIPTION_id_set(swigCPtr, this, FMOD_STUDIO_PARAMETER_ID.getCPtr(value), value);
  }

  public FMOD_STUDIO_PARAMETER_ID getId() {
    long cPtr = FMODStudioJNI.FMOD_STUDIO_PARAMETER_DESCRIPTION_id_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_STUDIO_PARAMETER_ID(cPtr, false);
  }

  public void setMinimum(float value) {
    FMODStudioJNI.FMOD_STUDIO_PARAMETER_DESCRIPTION_minimum_set(swigCPtr, this, value);
  }

  public float getMinimum() {
    return FMODStudioJNI.FMOD_STUDIO_PARAMETER_DESCRIPTION_minimum_get(swigCPtr, this);
  }

  public void setMaximum(float value) {
    FMODStudioJNI.FMOD_STUDIO_PARAMETER_DESCRIPTION_maximum_set(swigCPtr, this, value);
  }

  public float getMaximum() {
    return FMODStudioJNI.FMOD_STUDIO_PARAMETER_DESCRIPTION_maximum_get(swigCPtr, this);
  }

  public void setDefaultvalue(float value) {
    FMODStudioJNI.FMOD_STUDIO_PARAMETER_DESCRIPTION_defaultvalue_set(swigCPtr, this, value);
  }

  public float getDefaultvalue() {
    return FMODStudioJNI.FMOD_STUDIO_PARAMETER_DESCRIPTION_defaultvalue_get(swigCPtr, this);
  }

  public void setType(FMOD_STUDIO_PARAMETER_TYPE value) {
    FMODStudioJNI.FMOD_STUDIO_PARAMETER_DESCRIPTION_type_set(swigCPtr, this, value.swigValue());
  }

  public FMOD_STUDIO_PARAMETER_TYPE getType() {
    return FMOD_STUDIO_PARAMETER_TYPE.swigToEnum(FMODStudioJNI.FMOD_STUDIO_PARAMETER_DESCRIPTION_type_get(swigCPtr, this));
  }

  public void setFlags(long value) {
    FMODStudioJNI.FMOD_STUDIO_PARAMETER_DESCRIPTION_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return FMODStudioJNI.FMOD_STUDIO_PARAMETER_DESCRIPTION_flags_get(swigCPtr, this);
  }

  public void setGuid(FMOD_GUID value) {
    FMODStudioJNI.FMOD_STUDIO_PARAMETER_DESCRIPTION_guid_set(swigCPtr, this, FMOD_GUID.getCPtr(value), value);
  }

  public FMOD_GUID getGuid() {
    long cPtr = FMODStudioJNI.FMOD_STUDIO_PARAMETER_DESCRIPTION_guid_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_GUID(cPtr, false);
  }

  public FMOD_STUDIO_PARAMETER_DESCRIPTION() {
    this(FMODStudioJNI.new_FMOD_STUDIO_PARAMETER_DESCRIPTION(), true);
  }

}
