package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_CHORUS {
  public final static FMOD_DSP_CHORUS FMOD_DSP_CHORUS_MIX = new FMOD_DSP_CHORUS("FMOD_DSP_CHORUS_MIX");
  public final static FMOD_DSP_CHORUS FMOD_DSP_CHORUS_RATE = new FMOD_DSP_CHORUS("FMOD_DSP_CHORUS_RATE");
  public final static FMOD_DSP_CHORUS FMOD_DSP_CHORUS_DEPTH = new FMOD_DSP_CHORUS("FMOD_DSP_CHORUS_DEPTH");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_CHORUS swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_CHORUS.class + " with value " + swigValue);
  }

  private FMOD_DSP_CHORUS(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_CHORUS(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_CHORUS(String swigName, FMOD_DSP_CHORUS swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_CHORUS[] swigValues = { FMOD_DSP_CHORUS_MIX, FMOD_DSP_CHORUS_RATE, FMOD_DSP_CHORUS_DEPTH };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

