package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_MULTIBAND_EQ {
  public final static FMOD_DSP_MULTIBAND_EQ FMOD_DSP_MULTIBAND_EQ_A_FILTER = new FMOD_DSP_MULTIBAND_EQ("FMOD_DSP_MULTIBAND_EQ_A_FILTER");
  public final static FMOD_DSP_MULTIBAND_EQ FMOD_DSP_MULTIBAND_EQ_A_FREQUENCY = new FMOD_DSP_MULTIBAND_EQ("FMOD_DSP_MULTIBAND_EQ_A_FREQUENCY");
  public final static FMOD_DSP_MULTIBAND_EQ FMOD_DSP_MULTIBAND_EQ_A_Q = new FMOD_DSP_MULTIBAND_EQ("FMOD_DSP_MULTIBAND_EQ_A_Q");
  public final static FMOD_DSP_MULTIBAND_EQ FMOD_DSP_MULTIBAND_EQ_A_GAIN = new FMOD_DSP_MULTIBAND_EQ("FMOD_DSP_MULTIBAND_EQ_A_GAIN");
  public final static FMOD_DSP_MULTIBAND_EQ FMOD_DSP_MULTIBAND_EQ_B_FILTER = new FMOD_DSP_MULTIBAND_EQ("FMOD_DSP_MULTIBAND_EQ_B_FILTER");
  public final static FMOD_DSP_MULTIBAND_EQ FMOD_DSP_MULTIBAND_EQ_B_FREQUENCY = new FMOD_DSP_MULTIBAND_EQ("FMOD_DSP_MULTIBAND_EQ_B_FREQUENCY");
  public final static FMOD_DSP_MULTIBAND_EQ FMOD_DSP_MULTIBAND_EQ_B_Q = new FMOD_DSP_MULTIBAND_EQ("FMOD_DSP_MULTIBAND_EQ_B_Q");
  public final static FMOD_DSP_MULTIBAND_EQ FMOD_DSP_MULTIBAND_EQ_B_GAIN = new FMOD_DSP_MULTIBAND_EQ("FMOD_DSP_MULTIBAND_EQ_B_GAIN");
  public final static FMOD_DSP_MULTIBAND_EQ FMOD_DSP_MULTIBAND_EQ_C_FILTER = new FMOD_DSP_MULTIBAND_EQ("FMOD_DSP_MULTIBAND_EQ_C_FILTER");
  public final static FMOD_DSP_MULTIBAND_EQ FMOD_DSP_MULTIBAND_EQ_C_FREQUENCY = new FMOD_DSP_MULTIBAND_EQ("FMOD_DSP_MULTIBAND_EQ_C_FREQUENCY");
  public final static FMOD_DSP_MULTIBAND_EQ FMOD_DSP_MULTIBAND_EQ_C_Q = new FMOD_DSP_MULTIBAND_EQ("FMOD_DSP_MULTIBAND_EQ_C_Q");
  public final static FMOD_DSP_MULTIBAND_EQ FMOD_DSP_MULTIBAND_EQ_C_GAIN = new FMOD_DSP_MULTIBAND_EQ("FMOD_DSP_MULTIBAND_EQ_C_GAIN");
  public final static FMOD_DSP_MULTIBAND_EQ FMOD_DSP_MULTIBAND_EQ_D_FILTER = new FMOD_DSP_MULTIBAND_EQ("FMOD_DSP_MULTIBAND_EQ_D_FILTER");
  public final static FMOD_DSP_MULTIBAND_EQ FMOD_DSP_MULTIBAND_EQ_D_FREQUENCY = new FMOD_DSP_MULTIBAND_EQ("FMOD_DSP_MULTIBAND_EQ_D_FREQUENCY");
  public final static FMOD_DSP_MULTIBAND_EQ FMOD_DSP_MULTIBAND_EQ_D_Q = new FMOD_DSP_MULTIBAND_EQ("FMOD_DSP_MULTIBAND_EQ_D_Q");
  public final static FMOD_DSP_MULTIBAND_EQ FMOD_DSP_MULTIBAND_EQ_D_GAIN = new FMOD_DSP_MULTIBAND_EQ("FMOD_DSP_MULTIBAND_EQ_D_GAIN");
  public final static FMOD_DSP_MULTIBAND_EQ FMOD_DSP_MULTIBAND_EQ_E_FILTER = new FMOD_DSP_MULTIBAND_EQ("FMOD_DSP_MULTIBAND_EQ_E_FILTER");
  public final static FMOD_DSP_MULTIBAND_EQ FMOD_DSP_MULTIBAND_EQ_E_FREQUENCY = new FMOD_DSP_MULTIBAND_EQ("FMOD_DSP_MULTIBAND_EQ_E_FREQUENCY");
  public final static FMOD_DSP_MULTIBAND_EQ FMOD_DSP_MULTIBAND_EQ_E_Q = new FMOD_DSP_MULTIBAND_EQ("FMOD_DSP_MULTIBAND_EQ_E_Q");
  public final static FMOD_DSP_MULTIBAND_EQ FMOD_DSP_MULTIBAND_EQ_E_GAIN = new FMOD_DSP_MULTIBAND_EQ("FMOD_DSP_MULTIBAND_EQ_E_GAIN");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_MULTIBAND_EQ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_MULTIBAND_EQ.class + " with value " + swigValue);
  }

  private FMOD_DSP_MULTIBAND_EQ(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_MULTIBAND_EQ(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_MULTIBAND_EQ(String swigName, FMOD_DSP_MULTIBAND_EQ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_MULTIBAND_EQ[] swigValues = { FMOD_DSP_MULTIBAND_EQ_A_FILTER, FMOD_DSP_MULTIBAND_EQ_A_FREQUENCY, FMOD_DSP_MULTIBAND_EQ_A_Q, FMOD_DSP_MULTIBAND_EQ_A_GAIN, FMOD_DSP_MULTIBAND_EQ_B_FILTER, FMOD_DSP_MULTIBAND_EQ_B_FREQUENCY, FMOD_DSP_MULTIBAND_EQ_B_Q, FMOD_DSP_MULTIBAND_EQ_B_GAIN, FMOD_DSP_MULTIBAND_EQ_C_FILTER, FMOD_DSP_MULTIBAND_EQ_C_FREQUENCY, FMOD_DSP_MULTIBAND_EQ_C_Q, FMOD_DSP_MULTIBAND_EQ_C_GAIN, FMOD_DSP_MULTIBAND_EQ_D_FILTER, FMOD_DSP_MULTIBAND_EQ_D_FREQUENCY, FMOD_DSP_MULTIBAND_EQ_D_Q, FMOD_DSP_MULTIBAND_EQ_D_GAIN, FMOD_DSP_MULTIBAND_EQ_E_FILTER, FMOD_DSP_MULTIBAND_EQ_E_FREQUENCY, FMOD_DSP_MULTIBAND_EQ_E_Q, FMOD_DSP_MULTIBAND_EQ_E_GAIN };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

