package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_DSP_STATE_DFT_FUNCTIONS {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_DSP_STATE_DFT_FUNCTIONS(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_DSP_STATE_DFT_FUNCTIONS obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_DSP_STATE_DFT_FUNCTIONS obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_DSP_STATE_DFT_FUNCTIONS(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFftreal(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_q_const__float_p_struct_FMOD_COMPLEX_p_q_const__float_int__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_STATE_DFT_FUNCTIONS_fftreal_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_q_const__float_p_struct_FMOD_COMPLEX_p_q_const__float_int__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_q_const__float_p_struct_FMOD_COMPLEX_p_q_const__float_int__FMOD_RESULT getFftreal() {
    long cPtr = FMODStudioJNI.FMOD_DSP_STATE_DFT_FUNCTIONS_fftreal_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_q_const__float_p_struct_FMOD_COMPLEX_p_q_const__float_int__FMOD_RESULT(cPtr, false);
  }

  public void setInversefftreal(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_q_const__struct_FMOD_COMPLEX_p_float_p_q_const__float_int__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_STATE_DFT_FUNCTIONS_inversefftreal_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_q_const__struct_FMOD_COMPLEX_p_float_p_q_const__float_int__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_q_const__struct_FMOD_COMPLEX_p_float_p_q_const__float_int__FMOD_RESULT getInversefftreal() {
    long cPtr = FMODStudioJNI.FMOD_DSP_STATE_DFT_FUNCTIONS_inversefftreal_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_int_p_q_const__struct_FMOD_COMPLEX_p_float_p_q_const__float_int__FMOD_RESULT(cPtr, false);
  }

  public FMOD_DSP_STATE_DFT_FUNCTIONS() {
    this(FMODStudioJNI.new_FMOD_DSP_STATE_DFT_FUNCTIONS(), true);
  }

}
