package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_THREE_EQ {
  public final static FMOD_DSP_THREE_EQ FMOD_DSP_THREE_EQ_LOWGAIN = new FMOD_DSP_THREE_EQ("FMOD_DSP_THREE_EQ_LOWGAIN");
  public final static FMOD_DSP_THREE_EQ FMOD_DSP_THREE_EQ_MIDGAIN = new FMOD_DSP_THREE_EQ("FMOD_DSP_THREE_EQ_MIDGAIN");
  public final static FMOD_DSP_THREE_EQ FMOD_DSP_THREE_EQ_HIGHGAIN = new FMOD_DSP_THREE_EQ("FMOD_DSP_THREE_EQ_HIGHGAIN");
  public final static FMOD_DSP_THREE_EQ FMOD_DSP_THREE_EQ_LOWCROSSOVER = new FMOD_DSP_THREE_EQ("FMOD_DSP_THREE_EQ_LOWCROSSOVER");
  public final static FMOD_DSP_THREE_EQ FMOD_DSP_THREE_EQ_HIGHCROSSOVER = new FMOD_DSP_THREE_EQ("FMOD_DSP_THREE_EQ_HIGHCROSSOVER");
  public final static FMOD_DSP_THREE_EQ FMOD_DSP_THREE_EQ_CROSSOVERSLOPE = new FMOD_DSP_THREE_EQ("FMOD_DSP_THREE_EQ_CROSSOVERSLOPE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_THREE_EQ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_THREE_EQ.class + " with value " + swigValue);
  }

  private FMOD_DSP_THREE_EQ(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_THREE_EQ(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_THREE_EQ(String swigName, FMOD_DSP_THREE_EQ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_THREE_EQ[] swigValues = { FMOD_DSP_THREE_EQ_LOWGAIN, FMOD_DSP_THREE_EQ_MIDGAIN, FMOD_DSP_THREE_EQ_HIGHGAIN, FMOD_DSP_THREE_EQ_LOWCROSSOVER, FMOD_DSP_THREE_EQ_HIGHCROSSOVER, FMOD_DSP_THREE_EQ_CROSSOVERSLOPE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

