package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_DSP_BUFFER_ARRAY {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_DSP_BUFFER_ARRAY(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_DSP_BUFFER_ARRAY obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_DSP_BUFFER_ARRAY obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_DSP_BUFFER_ARRAY(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNumbuffers(int value) {
    FMODStudioJNI.FMOD_DSP_BUFFER_ARRAY_numbuffers_set(swigCPtr, this, value);
  }

  public int getNumbuffers() {
    return FMODStudioJNI.FMOD_DSP_BUFFER_ARRAY_numbuffers_get(swigCPtr, this);
  }

  public void setBuffernumchannels(SWIGTYPE_p_int value) {
    FMODStudioJNI.FMOD_DSP_BUFFER_ARRAY_buffernumchannels_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getBuffernumchannels() {
    long cPtr = FMODStudioJNI.FMOD_DSP_BUFFER_ARRAY_buffernumchannels_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setBufferchannelmask(SWIGTYPE_p_unsigned_int value) {
    FMODStudioJNI.FMOD_DSP_BUFFER_ARRAY_bufferchannelmask_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getBufferchannelmask() {
    long cPtr = FMODStudioJNI.FMOD_DSP_BUFFER_ARRAY_bufferchannelmask_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setBuffers(SWIGTYPE_p_p_float value) {
    FMODStudioJNI.FMOD_DSP_BUFFER_ARRAY_buffers_set(swigCPtr, this, SWIGTYPE_p_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_p_float getBuffers() {
    long cPtr = FMODStudioJNI.FMOD_DSP_BUFFER_ARRAY_buffers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_float(cPtr, false);
  }

  public void setSpeakermode(FMOD_SPEAKERMODE value) {
    FMODStudioJNI.FMOD_DSP_BUFFER_ARRAY_speakermode_set(swigCPtr, this, value.swigValue());
  }

  public FMOD_SPEAKERMODE getSpeakermode() {
    return FMOD_SPEAKERMODE.swigToEnum(FMODStudioJNI.FMOD_DSP_BUFFER_ARRAY_speakermode_get(swigCPtr, this));
  }

  public FMOD_DSP_BUFFER_ARRAY() {
    this(FMODStudioJNI.new_FMOD_DSP_BUFFER_ARRAY(), true);
  }

}
