package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_OBJECTPAN {
  public final static FMOD_DSP_OBJECTPAN FMOD_DSP_OBJECTPAN_3D_POSITION = new FMOD_DSP_OBJECTPAN("FMOD_DSP_OBJECTPAN_3D_POSITION");
  public final static FMOD_DSP_OBJECTPAN FMOD_DSP_OBJECTPAN_3D_ROLLOFF = new FMOD_DSP_OBJECTPAN("FMOD_DSP_OBJECTPAN_3D_ROLLOFF");
  public final static FMOD_DSP_OBJECTPAN FMOD_DSP_OBJECTPAN_3D_MIN_DISTANCE = new FMOD_DSP_OBJECTPAN("FMOD_DSP_OBJECTPAN_3D_MIN_DISTANCE");
  public final static FMOD_DSP_OBJECTPAN FMOD_DSP_OBJECTPAN_3D_MAX_DISTANCE = new FMOD_DSP_OBJECTPAN("FMOD_DSP_OBJECTPAN_3D_MAX_DISTANCE");
  public final static FMOD_DSP_OBJECTPAN FMOD_DSP_OBJECTPAN_3D_EXTENT_MODE = new FMOD_DSP_OBJECTPAN("FMOD_DSP_OBJECTPAN_3D_EXTENT_MODE");
  public final static FMOD_DSP_OBJECTPAN FMOD_DSP_OBJECTPAN_3D_SOUND_SIZE = new FMOD_DSP_OBJECTPAN("FMOD_DSP_OBJECTPAN_3D_SOUND_SIZE");
  public final static FMOD_DSP_OBJECTPAN FMOD_DSP_OBJECTPAN_3D_MIN_EXTENT = new FMOD_DSP_OBJECTPAN("FMOD_DSP_OBJECTPAN_3D_MIN_EXTENT");
  public final static FMOD_DSP_OBJECTPAN FMOD_DSP_OBJECTPAN_OVERALL_GAIN = new FMOD_DSP_OBJECTPAN("FMOD_DSP_OBJECTPAN_OVERALL_GAIN");
  public final static FMOD_DSP_OBJECTPAN FMOD_DSP_OBJECTPAN_OUTPUTGAIN = new FMOD_DSP_OBJECTPAN("FMOD_DSP_OBJECTPAN_OUTPUTGAIN");
  public final static FMOD_DSP_OBJECTPAN FMOD_DSP_OBJECTPAN_ATTENUATION_RANGE = new FMOD_DSP_OBJECTPAN("FMOD_DSP_OBJECTPAN_ATTENUATION_RANGE");
  public final static FMOD_DSP_OBJECTPAN FMOD_DSP_OBJECTPAN_OVERRIDE_RANGE = new FMOD_DSP_OBJECTPAN("FMOD_DSP_OBJECTPAN_OVERRIDE_RANGE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_OBJECTPAN swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_OBJECTPAN.class + " with value " + swigValue);
  }

  private FMOD_DSP_OBJECTPAN(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_OBJECTPAN(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_OBJECTPAN(String swigName, FMOD_DSP_OBJECTPAN swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_OBJECTPAN[] swigValues = { FMOD_DSP_OBJECTPAN_3D_POSITION, FMOD_DSP_OBJECTPAN_3D_ROLLOFF, FMOD_DSP_OBJECTPAN_3D_MIN_DISTANCE, FMOD_DSP_OBJECTPAN_3D_MAX_DISTANCE, FMOD_DSP_OBJECTPAN_3D_EXTENT_MODE, FMOD_DSP_OBJECTPAN_3D_SOUND_SIZE, FMOD_DSP_OBJECTPAN_3D_MIN_EXTENT, FMOD_DSP_OBJECTPAN_OVERALL_GAIN, FMOD_DSP_OBJECTPAN_OUTPUTGAIN, FMOD_DSP_OBJECTPAN_ATTENUATION_RANGE, FMOD_DSP_OBJECTPAN_OVERRIDE_RANGE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

