package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_CODEC_DESCRIPTION {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_CODEC_DESCRIPTION(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_CODEC_DESCRIPTION obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_CODEC_DESCRIPTION obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_CODEC_DESCRIPTION(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setApiversion(long value) {
    FMODStudioJNI.FMOD_CODEC_DESCRIPTION_apiversion_set(swigCPtr, this, value);
  }

  public long getApiversion() {
    return FMODStudioJNI.FMOD_CODEC_DESCRIPTION_apiversion_get(swigCPtr, this);
  }

  public void setName(String value) {
    FMODStudioJNI.FMOD_CODEC_DESCRIPTION_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return FMODStudioJNI.FMOD_CODEC_DESCRIPTION_name_get(swigCPtr, this);
  }

  public void setVersion(long value) {
    FMODStudioJNI.FMOD_CODEC_DESCRIPTION_version_set(swigCPtr, this, value);
  }

  public long getVersion() {
    return FMODStudioJNI.FMOD_CODEC_DESCRIPTION_version_get(swigCPtr, this);
  }

  public void setDefaultasstream(int value) {
    FMODStudioJNI.FMOD_CODEC_DESCRIPTION_defaultasstream_set(swigCPtr, this, value);
  }

  public int getDefaultasstream() {
    return FMODStudioJNI.FMOD_CODEC_DESCRIPTION_defaultasstream_get(swigCPtr, this);
  }

  public void setTimeunits(long value) {
    FMODStudioJNI.FMOD_CODEC_DESCRIPTION_timeunits_set(swigCPtr, this, value);
  }

  public long getTimeunits() {
    return FMODStudioJNI.FMOD_CODEC_DESCRIPTION_timeunits_get(swigCPtr, this);
  }

  public void setOpen(SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_unsigned_int_p_struct_FMOD_CREATESOUNDEXINFO__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_CODEC_DESCRIPTION_open_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_unsigned_int_p_struct_FMOD_CREATESOUNDEXINFO__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_unsigned_int_p_struct_FMOD_CREATESOUNDEXINFO__FMOD_RESULT getOpen() {
    long cPtr = FMODStudioJNI.FMOD_CODEC_DESCRIPTION_open_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_unsigned_int_p_struct_FMOD_CREATESOUNDEXINFO__FMOD_RESULT(cPtr, false);
  }

  public void setClose(SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_CODEC_DESCRIPTION_close_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE__FMOD_RESULT getClose() {
    long cPtr = FMODStudioJNI.FMOD_CODEC_DESCRIPTION_close_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE__FMOD_RESULT(cPtr, false);
  }

  public void setRead(SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_p_void_unsigned_int_p_unsigned_int__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_CODEC_DESCRIPTION_read_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_p_void_unsigned_int_p_unsigned_int__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_p_void_unsigned_int_p_unsigned_int__FMOD_RESULT getRead() {
    long cPtr = FMODStudioJNI.FMOD_CODEC_DESCRIPTION_read_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_p_void_unsigned_int_p_unsigned_int__FMOD_RESULT(cPtr, false);
  }

  public void setGetlength(SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_p_unsigned_int_unsigned_int__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_CODEC_DESCRIPTION_getlength_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_p_unsigned_int_unsigned_int__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_p_unsigned_int_unsigned_int__FMOD_RESULT getGetlength() {
    long cPtr = FMODStudioJNI.FMOD_CODEC_DESCRIPTION_getlength_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_p_unsigned_int_unsigned_int__FMOD_RESULT(cPtr, false);
  }

  public void setSetposition(SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_int_unsigned_int_unsigned_int__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_CODEC_DESCRIPTION_setposition_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_int_unsigned_int_unsigned_int__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_int_unsigned_int_unsigned_int__FMOD_RESULT getSetposition() {
    long cPtr = FMODStudioJNI.FMOD_CODEC_DESCRIPTION_setposition_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_int_unsigned_int_unsigned_int__FMOD_RESULT(cPtr, false);
  }

  public void setGetposition(SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_p_unsigned_int_unsigned_int__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_CODEC_DESCRIPTION_getposition_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_p_unsigned_int_unsigned_int__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_p_unsigned_int_unsigned_int__FMOD_RESULT getGetposition() {
    long cPtr = FMODStudioJNI.FMOD_CODEC_DESCRIPTION_getposition_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_p_unsigned_int_unsigned_int__FMOD_RESULT(cPtr, false);
  }

  public void setSoundcreate(SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_int_p_struct_FMOD_SOUND__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_CODEC_DESCRIPTION_soundcreate_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_int_p_struct_FMOD_SOUND__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_int_p_struct_FMOD_SOUND__FMOD_RESULT getSoundcreate() {
    long cPtr = FMODStudioJNI.FMOD_CODEC_DESCRIPTION_soundcreate_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_int_p_struct_FMOD_SOUND__FMOD_RESULT(cPtr, false);
  }

  public void setGetwaveformat(SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_int_p_struct_FMOD_CODEC_WAVEFORMAT__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_CODEC_DESCRIPTION_getwaveformat_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_int_p_struct_FMOD_CODEC_WAVEFORMAT__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_int_p_struct_FMOD_CODEC_WAVEFORMAT__FMOD_RESULT getGetwaveformat() {
    long cPtr = FMODStudioJNI.FMOD_CODEC_DESCRIPTION_getwaveformat_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_CODEC_STATE_int_p_struct_FMOD_CODEC_WAVEFORMAT__FMOD_RESULT(cPtr, false);
  }

  public FMOD_CODEC_DESCRIPTION() {
    this(FMODStudioJNI.new_FMOD_CODEC_DESCRIPTION(), true);
  }

}
