package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_CODEC_STATE {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_CODEC_STATE(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_CODEC_STATE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_CODEC_STATE obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_CODEC_STATE(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPlugindata(SWIGTYPE_p_void value) {
    FMODStudioJNI.FMOD_CODEC_STATE_plugindata_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getPlugindata() {
    long cPtr = FMODStudioJNI.FMOD_CODEC_STATE_plugindata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setWaveformat(FMOD_CODEC_WAVEFORMAT value) {
    FMODStudioJNI.FMOD_CODEC_STATE_waveformat_set(swigCPtr, this, FMOD_CODEC_WAVEFORMAT.getCPtr(value), value);
  }

  public FMOD_CODEC_WAVEFORMAT getWaveformat() {
    long cPtr = FMODStudioJNI.FMOD_CODEC_STATE_waveformat_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_CODEC_WAVEFORMAT(cPtr, false);
  }

  public void setFunctions(FMOD_CODEC_STATE_FUNCTIONS value) {
    FMODStudioJNI.FMOD_CODEC_STATE_functions_set(swigCPtr, this, FMOD_CODEC_STATE_FUNCTIONS.getCPtr(value), value);
  }

  public FMOD_CODEC_STATE_FUNCTIONS getFunctions() {
    long cPtr = FMODStudioJNI.FMOD_CODEC_STATE_functions_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_CODEC_STATE_FUNCTIONS(cPtr, false);
  }

  public void setNumsubsounds(int value) {
    FMODStudioJNI.FMOD_CODEC_STATE_numsubsounds_set(swigCPtr, this, value);
  }

  public int getNumsubsounds() {
    return FMODStudioJNI.FMOD_CODEC_STATE_numsubsounds_get(swigCPtr, this);
  }

  public FMOD_CODEC_STATE() {
    this(FMODStudioJNI.new_FMOD_CODEC_STATE(), true);
  }

}
