package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_DSP_PARAMETER_FFT {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_DSP_PARAMETER_FFT(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_DSP_PARAMETER_FFT obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_DSP_PARAMETER_FFT obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_DSP_PARAMETER_FFT(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLength(int value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_FFT_length_set(swigCPtr, this, value);
  }

  public int getLength() {
    return FMODStudioJNI.FMOD_DSP_PARAMETER_FFT_length_get(swigCPtr, this);
  }

  public void setNumchannels(int value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_FFT_numchannels_set(swigCPtr, this, value);
  }

  public int getNumchannels() {
    return FMODStudioJNI.FMOD_DSP_PARAMETER_FFT_numchannels_get(swigCPtr, this);
  }

  public void setSpectrum(SWIGTYPE_p_p_float value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_FFT_spectrum_set(swigCPtr, this, SWIGTYPE_p_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_p_float getSpectrum() {
    long cPtr = FMODStudioJNI.FMOD_DSP_PARAMETER_FFT_spectrum_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_float(cPtr, false);
  }

  public FMOD_DSP_PARAMETER_FFT() {
    this(FMODStudioJNI.new_FMOD_DSP_PARAMETER_FFT(), true);
  }

}
