package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_RETURN {
  public final static FMOD_DSP_RETURN FMOD_DSP_RETURN_ID = new FMOD_DSP_RETURN("FMOD_DSP_RETURN_ID");
  public final static FMOD_DSP_RETURN FMOD_DSP_RETURN_INPUT_SPEAKER_MODE = new FMOD_DSP_RETURN("FMOD_DSP_RETURN_INPUT_SPEAKER_MODE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_RETURN swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_RETURN.class + " with value " + swigValue);
  }

  private FMOD_DSP_RETURN(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_RETURN(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_RETURN(String swigName, FMOD_DSP_RETURN swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_RETURN[] swigValues = { FMOD_DSP_RETURN_ID, FMOD_DSP_RETURN_INPUT_SPEAKER_MODE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

