package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_DSP_PARAMETER_DESC {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_DSP_PARAMETER_DESC(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_DSP_PARAMETER_DESC obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_DSP_PARAMETER_DESC obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_DSP_PARAMETER_DESC(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(FMOD_DSP_PARAMETER_TYPE value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_type_set(swigCPtr, this, value.swigValue());
  }

  public FMOD_DSP_PARAMETER_TYPE getType() {
    return FMOD_DSP_PARAMETER_TYPE.swigToEnum(FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_type_get(swigCPtr, this));
  }

  public void setName(String value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_name_get(swigCPtr, this);
  }

  public void setLabel(String value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_label_set(swigCPtr, this, value);
  }

  public String getLabel() {
    return FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_label_get(swigCPtr, this);
  }

  public void setDescription(String value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_description_set(swigCPtr, this, value);
  }

  public String getDescription() {
    return FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_description_get(swigCPtr, this);
  }

  public void setFloatdesc(FMOD_DSP_PARAMETER_DESC_FLOAT value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_floatdesc_set(swigCPtr, this, FMOD_DSP_PARAMETER_DESC_FLOAT.getCPtr(value), value);
  }

  public FMOD_DSP_PARAMETER_DESC_FLOAT getFloatdesc() {
    long cPtr = FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_floatdesc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_DSP_PARAMETER_DESC_FLOAT(cPtr, false);
  }

  public void setIntdesc(FMOD_DSP_PARAMETER_DESC_INT value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_intdesc_set(swigCPtr, this, FMOD_DSP_PARAMETER_DESC_INT.getCPtr(value), value);
  }

  public FMOD_DSP_PARAMETER_DESC_INT getIntdesc() {
    long cPtr = FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_intdesc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_DSP_PARAMETER_DESC_INT(cPtr, false);
  }

  public void setBooldesc(FMOD_DSP_PARAMETER_DESC_BOOL value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_booldesc_set(swigCPtr, this, FMOD_DSP_PARAMETER_DESC_BOOL.getCPtr(value), value);
  }

  public FMOD_DSP_PARAMETER_DESC_BOOL getBooldesc() {
    long cPtr = FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_booldesc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_DSP_PARAMETER_DESC_BOOL(cPtr, false);
  }

  public void setDatadesc(FMOD_DSP_PARAMETER_DESC_DATA value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_datadesc_set(swigCPtr, this, FMOD_DSP_PARAMETER_DESC_DATA.getCPtr(value), value);
  }

  public FMOD_DSP_PARAMETER_DESC_DATA getDatadesc() {
    long cPtr = FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_datadesc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_DSP_PARAMETER_DESC_DATA(cPtr, false);
  }

  public FMOD_DSP_PARAMETER_DESC() {
    this(FMODStudioJNI.new_FMOD_DSP_PARAMETER_DESC(), true);
  }

}
