package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_STUDIO_SOUND_INFO {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_STUDIO_SOUND_INFO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_STUDIO_SOUND_INFO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_STUDIO_SOUND_INFO obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_STUDIO_SOUND_INFO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName_or_data(String value) {
    FMODStudioJNI.FMOD_STUDIO_SOUND_INFO_name_or_data_set(swigCPtr, this, value);
  }

  public String getName_or_data() {
    return FMODStudioJNI.FMOD_STUDIO_SOUND_INFO_name_or_data_get(swigCPtr, this);
  }

  public void setMode(long value) {
    FMODStudioJNI.FMOD_STUDIO_SOUND_INFO_mode_set(swigCPtr, this, value);
  }

  public long getMode() {
    return FMODStudioJNI.FMOD_STUDIO_SOUND_INFO_mode_get(swigCPtr, this);
  }

  public void setExinfo(FMOD_CREATESOUNDEXINFO value) {
    FMODStudioJNI.FMOD_STUDIO_SOUND_INFO_exinfo_set(swigCPtr, this, FMOD_CREATESOUNDEXINFO.getCPtr(value), value);
  }

  public FMOD_CREATESOUNDEXINFO getExinfo() {
    long cPtr = FMODStudioJNI.FMOD_STUDIO_SOUND_INFO_exinfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_CREATESOUNDEXINFO(cPtr, false);
  }

  public void setSubsoundindex(int value) {
    FMODStudioJNI.FMOD_STUDIO_SOUND_INFO_subsoundindex_set(swigCPtr, this, value);
  }

  public int getSubsoundindex() {
    return FMODStudioJNI.FMOD_STUDIO_SOUND_INFO_subsoundindex_get(swigCPtr, this);
  }

  public FMOD_STUDIO_SOUND_INFO() {
    this(FMODStudioJNI.new_FMOD_STUDIO_SOUND_INFO(), true);
  }

}
