package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_DSP_PARAMETER_FLOAT_MAPPING_PIECEWISE_LINEAR {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_DSP_PARAMETER_FLOAT_MAPPING_PIECEWISE_LINEAR(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_DSP_PARAMETER_FLOAT_MAPPING_PIECEWISE_LINEAR obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_DSP_PARAMETER_FLOAT_MAPPING_PIECEWISE_LINEAR obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_DSP_PARAMETER_FLOAT_MAPPING_PIECEWISE_LINEAR(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNumpoints(int value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_FLOAT_MAPPING_PIECEWISE_LINEAR_numpoints_set(swigCPtr, this, value);
  }

  public int getNumpoints() {
    return FMODStudioJNI.FMOD_DSP_PARAMETER_FLOAT_MAPPING_PIECEWISE_LINEAR_numpoints_get(swigCPtr, this);
  }

  public void setPointparamvalues(SWIGTYPE_p_float value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_FLOAT_MAPPING_PIECEWISE_LINEAR_pointparamvalues_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getPointparamvalues() {
    long cPtr = FMODStudioJNI.FMOD_DSP_PARAMETER_FLOAT_MAPPING_PIECEWISE_LINEAR_pointparamvalues_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setPointpositions(SWIGTYPE_p_float value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_FLOAT_MAPPING_PIECEWISE_LINEAR_pointpositions_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getPointpositions() {
    long cPtr = FMODStudioJNI.FMOD_DSP_PARAMETER_FLOAT_MAPPING_PIECEWISE_LINEAR_pointpositions_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public FMOD_DSP_PARAMETER_FLOAT_MAPPING_PIECEWISE_LINEAR() {
    this(FMODStudioJNI.new_FMOD_DSP_PARAMETER_FLOAT_MAPPING_PIECEWISE_LINEAR(), true);
  }

}
