package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_TRANSCEIVER {
  public final static FMOD_DSP_TRANSCEIVER FMOD_DSP_TRANSCEIVER_TRANSMIT = new FMOD_DSP_TRANSCEIVER("FMOD_DSP_TRANSCEIVER_TRANSMIT");
  public final static FMOD_DSP_TRANSCEIVER FMOD_DSP_TRANSCEIVER_GAIN = new FMOD_DSP_TRANSCEIVER("FMOD_DSP_TRANSCEIVER_GAIN");
  public final static FMOD_DSP_TRANSCEIVER FMOD_DSP_TRANSCEIVER_CHANNEL = new FMOD_DSP_TRANSCEIVER("FMOD_DSP_TRANSCEIVER_CHANNEL");
  public final static FMOD_DSP_TRANSCEIVER FMOD_DSP_TRANSCEIVER_TRANSMITSPEAKERMODE = new FMOD_DSP_TRANSCEIVER("FMOD_DSP_TRANSCEIVER_TRANSMITSPEAKERMODE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_TRANSCEIVER swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_TRANSCEIVER.class + " with value " + swigValue);
  }

  private FMOD_DSP_TRANSCEIVER(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_TRANSCEIVER(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_TRANSCEIVER(String swigName, FMOD_DSP_TRANSCEIVER swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_TRANSCEIVER[] swigValues = { FMOD_DSP_TRANSCEIVER_TRANSMIT, FMOD_DSP_TRANSCEIVER_GAIN, FMOD_DSP_TRANSCEIVER_CHANNEL, FMOD_DSP_TRANSCEIVER_TRANSMITSPEAKERMODE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

