package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_CHANNELMIX_OUTPUT {
  public final static FMOD_DSP_CHANNELMIX_OUTPUT FMOD_DSP_CHANNELMIX_OUTPUT_DEFAULT = new FMOD_DSP_CHANNELMIX_OUTPUT("FMOD_DSP_CHANNELMIX_OUTPUT_DEFAULT");
  public final static FMOD_DSP_CHANNELMIX_OUTPUT FMOD_DSP_CHANNELMIX_OUTPUT_ALLMONO = new FMOD_DSP_CHANNELMIX_OUTPUT("FMOD_DSP_CHANNELMIX_OUTPUT_ALLMONO");
  public final static FMOD_DSP_CHANNELMIX_OUTPUT FMOD_DSP_CHANNELMIX_OUTPUT_ALLSTEREO = new FMOD_DSP_CHANNELMIX_OUTPUT("FMOD_DSP_CHANNELMIX_OUTPUT_ALLSTEREO");
  public final static FMOD_DSP_CHANNELMIX_OUTPUT FMOD_DSP_CHANNELMIX_OUTPUT_ALLQUAD = new FMOD_DSP_CHANNELMIX_OUTPUT("FMOD_DSP_CHANNELMIX_OUTPUT_ALLQUAD");
  public final static FMOD_DSP_CHANNELMIX_OUTPUT FMOD_DSP_CHANNELMIX_OUTPUT_ALL5POINT1 = new FMOD_DSP_CHANNELMIX_OUTPUT("FMOD_DSP_CHANNELMIX_OUTPUT_ALL5POINT1");
  public final static FMOD_DSP_CHANNELMIX_OUTPUT FMOD_DSP_CHANNELMIX_OUTPUT_ALL7POINT1 = new FMOD_DSP_CHANNELMIX_OUTPUT("FMOD_DSP_CHANNELMIX_OUTPUT_ALL7POINT1");
  public final static FMOD_DSP_CHANNELMIX_OUTPUT FMOD_DSP_CHANNELMIX_OUTPUT_ALLLFE = new FMOD_DSP_CHANNELMIX_OUTPUT("FMOD_DSP_CHANNELMIX_OUTPUT_ALLLFE");
  public final static FMOD_DSP_CHANNELMIX_OUTPUT FMOD_DSP_CHANNELMIX_OUTPUT_ALL7POINT1POINT4 = new FMOD_DSP_CHANNELMIX_OUTPUT("FMOD_DSP_CHANNELMIX_OUTPUT_ALL7POINT1POINT4");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_CHANNELMIX_OUTPUT swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_CHANNELMIX_OUTPUT.class + " with value " + swigValue);
  }

  private FMOD_DSP_CHANNELMIX_OUTPUT(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_CHANNELMIX_OUTPUT(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_CHANNELMIX_OUTPUT(String swigName, FMOD_DSP_CHANNELMIX_OUTPUT swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_CHANNELMIX_OUTPUT[] swigValues = { FMOD_DSP_CHANNELMIX_OUTPUT_DEFAULT, FMOD_DSP_CHANNELMIX_OUTPUT_ALLMONO, FMOD_DSP_CHANNELMIX_OUTPUT_ALLSTEREO, FMOD_DSP_CHANNELMIX_OUTPUT_ALLQUAD, FMOD_DSP_CHANNELMIX_OUTPUT_ALL5POINT1, FMOD_DSP_CHANNELMIX_OUTPUT_ALL7POINT1, FMOD_DSP_CHANNELMIX_OUTPUT_ALLLFE, FMOD_DSP_CHANNELMIX_OUTPUT_ALL7POINT1POINT4 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

