package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_STUDIO_PARAMETER_ID {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_STUDIO_PARAMETER_ID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_STUDIO_PARAMETER_ID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_STUDIO_PARAMETER_ID obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_STUDIO_PARAMETER_ID(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData1(long value) {
    FMODStudioJNI.FMOD_STUDIO_PARAMETER_ID_data1_set(swigCPtr, this, value);
  }

  public long getData1() {
    return FMODStudioJNI.FMOD_STUDIO_PARAMETER_ID_data1_get(swigCPtr, this);
  }

  public void setData2(long value) {
    FMODStudioJNI.FMOD_STUDIO_PARAMETER_ID_data2_set(swigCPtr, this, value);
  }

  public long getData2() {
    return FMODStudioJNI.FMOD_STUDIO_PARAMETER_ID_data2_get(swigCPtr, this);
  }

  public FMOD_STUDIO_PARAMETER_ID() {
    this(FMODStudioJNI.new_FMOD_STUDIO_PARAMETER_ID(), true);
  }

}
