package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_SOUND_FORMAT {
  public final static FMOD_SOUND_FORMAT FMOD_SOUND_FORMAT_NONE = new FMOD_SOUND_FORMAT("FMOD_SOUND_FORMAT_NONE");
  public final static FMOD_SOUND_FORMAT FMOD_SOUND_FORMAT_PCM8 = new FMOD_SOUND_FORMAT("FMOD_SOUND_FORMAT_PCM8");
  public final static FMOD_SOUND_FORMAT FMOD_SOUND_FORMAT_PCM16 = new FMOD_SOUND_FORMAT("FMOD_SOUND_FORMAT_PCM16");
  public final static FMOD_SOUND_FORMAT FMOD_SOUND_FORMAT_PCM24 = new FMOD_SOUND_FORMAT("FMOD_SOUND_FORMAT_PCM24");
  public final static FMOD_SOUND_FORMAT FMOD_SOUND_FORMAT_PCM32 = new FMOD_SOUND_FORMAT("FMOD_SOUND_FORMAT_PCM32");
  public final static FMOD_SOUND_FORMAT FMOD_SOUND_FORMAT_PCMFLOAT = new FMOD_SOUND_FORMAT("FMOD_SOUND_FORMAT_PCMFLOAT");
  public final static FMOD_SOUND_FORMAT FMOD_SOUND_FORMAT_BITSTREAM = new FMOD_SOUND_FORMAT("FMOD_SOUND_FORMAT_BITSTREAM");
  public final static FMOD_SOUND_FORMAT FMOD_SOUND_FORMAT_MAX = new FMOD_SOUND_FORMAT("FMOD_SOUND_FORMAT_MAX");
  public final static FMOD_SOUND_FORMAT FMOD_SOUND_FORMAT_FORCEINT = new FMOD_SOUND_FORMAT("FMOD_SOUND_FORMAT_FORCEINT", FMODStudioJNI.FMOD_SOUND_FORMAT_FORCEINT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_SOUND_FORMAT swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_SOUND_FORMAT.class + " with value " + swigValue);
  }

  private FMOD_SOUND_FORMAT(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_SOUND_FORMAT(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_SOUND_FORMAT(String swigName, FMOD_SOUND_FORMAT swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_SOUND_FORMAT[] swigValues = { FMOD_SOUND_FORMAT_NONE, FMOD_SOUND_FORMAT_PCM8, FMOD_SOUND_FORMAT_PCM16, FMOD_SOUND_FORMAT_PCM24, FMOD_SOUND_FORMAT_PCM32, FMOD_SOUND_FORMAT_PCMFLOAT, FMOD_SOUND_FORMAT_BITSTREAM, FMOD_SOUND_FORMAT_MAX, FMOD_SOUND_FORMAT_FORCEINT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

