package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_3D_ATTRIBUTES {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_3D_ATTRIBUTES(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_3D_ATTRIBUTES obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_3D_ATTRIBUTES obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_3D_ATTRIBUTES(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPosition(FMOD_VECTOR value) {
    FMODStudioJNI.FMOD_3D_ATTRIBUTES_position_set(swigCPtr, this, FMOD_VECTOR.getCPtr(value), value);
  }

  public FMOD_VECTOR getPosition() {
    long cPtr = FMODStudioJNI.FMOD_3D_ATTRIBUTES_position_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_VECTOR(cPtr, false);
  }

  public void setVelocity(FMOD_VECTOR value) {
    FMODStudioJNI.FMOD_3D_ATTRIBUTES_velocity_set(swigCPtr, this, FMOD_VECTOR.getCPtr(value), value);
  }

  public FMOD_VECTOR getVelocity() {
    long cPtr = FMODStudioJNI.FMOD_3D_ATTRIBUTES_velocity_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_VECTOR(cPtr, false);
  }

  public void setForward(FMOD_VECTOR value) {
    FMODStudioJNI.FMOD_3D_ATTRIBUTES_forward_set(swigCPtr, this, FMOD_VECTOR.getCPtr(value), value);
  }

  public FMOD_VECTOR getForward() {
    long cPtr = FMODStudioJNI.FMOD_3D_ATTRIBUTES_forward_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_VECTOR(cPtr, false);
  }

  public void setUp(FMOD_VECTOR value) {
    FMODStudioJNI.FMOD_3D_ATTRIBUTES_up_set(swigCPtr, this, FMOD_VECTOR.getCPtr(value), value);
  }

  public FMOD_VECTOR getUp() {
    long cPtr = FMODStudioJNI.FMOD_3D_ATTRIBUTES_up_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_VECTOR(cPtr, false);
  }

  public FMOD_3D_ATTRIBUTES() {
    this(FMODStudioJNI.new_FMOD_3D_ATTRIBUTES(), true);
  }

}
