package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_DSP_PARAMETER_DESC_BOOL {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_DSP_PARAMETER_DESC_BOOL(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_DSP_PARAMETER_DESC_BOOL obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_DSP_PARAMETER_DESC_BOOL obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_DSP_PARAMETER_DESC_BOOL(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDefaultval(int value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_BOOL_defaultval_set(swigCPtr, this, value);
  }

  public int getDefaultval() {
    return FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_BOOL_defaultval_get(swigCPtr, this);
  }

  public void setValuenames(SWIGTYPE_p_p_char value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_BOOL_valuenames_set(swigCPtr, this, SWIGTYPE_p_p_char.getCPtr(value));
  }

  public SWIGTYPE_p_p_char getValuenames() {
    long cPtr = FMODStudioJNI.FMOD_DSP_PARAMETER_DESC_BOOL_valuenames_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public FMOD_DSP_PARAMETER_DESC_BOOL() {
    this(FMODStudioJNI.new_FMOD_DSP_PARAMETER_DESC_BOOL(), true);
  }

}
