package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_LOUDNESS_METER_STATE_TYPE {
  public final static FMOD_DSP_LOUDNESS_METER_STATE_TYPE FMOD_DSP_LOUDNESS_METER_STATE_RESET_INTEGRATED = new FMOD_DSP_LOUDNESS_METER_STATE_TYPE("FMOD_DSP_LOUDNESS_METER_STATE_RESET_INTEGRATED", FMODStudioJNI.FMOD_DSP_LOUDNESS_METER_STATE_RESET_INTEGRATED_get());
  public final static FMOD_DSP_LOUDNESS_METER_STATE_TYPE FMOD_DSP_LOUDNESS_METER_STATE_RESET_MAXPEAK = new FMOD_DSP_LOUDNESS_METER_STATE_TYPE("FMOD_DSP_LOUDNESS_METER_STATE_RESET_MAXPEAK", FMODStudioJNI.FMOD_DSP_LOUDNESS_METER_STATE_RESET_MAXPEAK_get());
  public final static FMOD_DSP_LOUDNESS_METER_STATE_TYPE FMOD_DSP_LOUDNESS_METER_STATE_RESET_ALL = new FMOD_DSP_LOUDNESS_METER_STATE_TYPE("FMOD_DSP_LOUDNESS_METER_STATE_RESET_ALL", FMODStudioJNI.FMOD_DSP_LOUDNESS_METER_STATE_RESET_ALL_get());
  public final static FMOD_DSP_LOUDNESS_METER_STATE_TYPE FMOD_DSP_LOUDNESS_METER_STATE_PAUSED = new FMOD_DSP_LOUDNESS_METER_STATE_TYPE("FMOD_DSP_LOUDNESS_METER_STATE_PAUSED", FMODStudioJNI.FMOD_DSP_LOUDNESS_METER_STATE_PAUSED_get());
  public final static FMOD_DSP_LOUDNESS_METER_STATE_TYPE FMOD_DSP_LOUDNESS_METER_STATE_ANALYZING = new FMOD_DSP_LOUDNESS_METER_STATE_TYPE("FMOD_DSP_LOUDNESS_METER_STATE_ANALYZING", FMODStudioJNI.FMOD_DSP_LOUDNESS_METER_STATE_ANALYZING_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_LOUDNESS_METER_STATE_TYPE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_LOUDNESS_METER_STATE_TYPE.class + " with value " + swigValue);
  }

  private FMOD_DSP_LOUDNESS_METER_STATE_TYPE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_LOUDNESS_METER_STATE_TYPE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_LOUDNESS_METER_STATE_TYPE(String swigName, FMOD_DSP_LOUDNESS_METER_STATE_TYPE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_LOUDNESS_METER_STATE_TYPE[] swigValues = { FMOD_DSP_LOUDNESS_METER_STATE_RESET_INTEGRATED, FMOD_DSP_LOUDNESS_METER_STATE_RESET_MAXPEAK, FMOD_DSP_LOUDNESS_METER_STATE_RESET_ALL, FMOD_DSP_LOUDNESS_METER_STATE_PAUSED, FMOD_DSP_LOUDNESS_METER_STATE_ANALYZING };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

