package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_DSP_PARAMETER_FLOAT_MAPPING {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_DSP_PARAMETER_FLOAT_MAPPING(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_DSP_PARAMETER_FLOAT_MAPPING obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_DSP_PARAMETER_FLOAT_MAPPING obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_DSP_PARAMETER_FLOAT_MAPPING(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(FMOD_DSP_PARAMETER_FLOAT_MAPPING_TYPE value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_FLOAT_MAPPING_type_set(swigCPtr, this, value.swigValue());
  }

  public FMOD_DSP_PARAMETER_FLOAT_MAPPING_TYPE getType() {
    return FMOD_DSP_PARAMETER_FLOAT_MAPPING_TYPE.swigToEnum(FMODStudioJNI.FMOD_DSP_PARAMETER_FLOAT_MAPPING_type_get(swigCPtr, this));
  }

  public void setPiecewiselinearmapping(FMOD_DSP_PARAMETER_FLOAT_MAPPING_PIECEWISE_LINEAR value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_FLOAT_MAPPING_piecewiselinearmapping_set(swigCPtr, this, FMOD_DSP_PARAMETER_FLOAT_MAPPING_PIECEWISE_LINEAR.getCPtr(value), value);
  }

  public FMOD_DSP_PARAMETER_FLOAT_MAPPING_PIECEWISE_LINEAR getPiecewiselinearmapping() {
    long cPtr = FMODStudioJNI.FMOD_DSP_PARAMETER_FLOAT_MAPPING_piecewiselinearmapping_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_DSP_PARAMETER_FLOAT_MAPPING_PIECEWISE_LINEAR(cPtr, false);
  }

  public FMOD_DSP_PARAMETER_FLOAT_MAPPING() {
    this(FMODStudioJNI.new_FMOD_DSP_PARAMETER_FLOAT_MAPPING(), true);
  }

}
