package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_STUDIO_USER_PROPERTY {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_STUDIO_USER_PROPERTY(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_STUDIO_USER_PROPERTY obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_STUDIO_USER_PROPERTY obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_STUDIO_USER_PROPERTY(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    FMODStudioJNI.FMOD_STUDIO_USER_PROPERTY_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return FMODStudioJNI.FMOD_STUDIO_USER_PROPERTY_name_get(swigCPtr, this);
  }

  public void setType(FMOD_STUDIO_USER_PROPERTY_TYPE value) {
    FMODStudioJNI.FMOD_STUDIO_USER_PROPERTY_type_set(swigCPtr, this, value.swigValue());
  }

  public FMOD_STUDIO_USER_PROPERTY_TYPE getType() {
    return FMOD_STUDIO_USER_PROPERTY_TYPE.swigToEnum(FMODStudioJNI.FMOD_STUDIO_USER_PROPERTY_type_get(swigCPtr, this));
  }

  public void setIntvalue(int value) {
    FMODStudioJNI.FMOD_STUDIO_USER_PROPERTY_intvalue_set(swigCPtr, this, value);
  }

  public int getIntvalue() {
    return FMODStudioJNI.FMOD_STUDIO_USER_PROPERTY_intvalue_get(swigCPtr, this);
  }

  public void setBoolvalue(int value) {
    FMODStudioJNI.FMOD_STUDIO_USER_PROPERTY_boolvalue_set(swigCPtr, this, value);
  }

  public int getBoolvalue() {
    return FMODStudioJNI.FMOD_STUDIO_USER_PROPERTY_boolvalue_get(swigCPtr, this);
  }

  public void setFloatvalue(float value) {
    FMODStudioJNI.FMOD_STUDIO_USER_PROPERTY_floatvalue_set(swigCPtr, this, value);
  }

  public float getFloatvalue() {
    return FMODStudioJNI.FMOD_STUDIO_USER_PROPERTY_floatvalue_get(swigCPtr, this);
  }

  public void setStringvalue(String value) {
    FMODStudioJNI.FMOD_STUDIO_USER_PROPERTY_stringvalue_set(swigCPtr, this, value);
  }

  public String getStringvalue() {
    return FMODStudioJNI.FMOD_STUDIO_USER_PROPERTY_stringvalue_get(swigCPtr, this);
  }

  public FMOD_STUDIO_USER_PROPERTY() {
    this(FMODStudioJNI.new_FMOD_STUDIO_USER_PROPERTY(), true);
  }

}
