package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_DSP_PARAMETER_3DATTRIBUTES_MULTI {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_DSP_PARAMETER_3DATTRIBUTES_MULTI(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_DSP_PARAMETER_3DATTRIBUTES_MULTI obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_DSP_PARAMETER_3DATTRIBUTES_MULTI obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_DSP_PARAMETER_3DATTRIBUTES_MULTI(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNumlisteners(int value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_3DATTRIBUTES_MULTI_numlisteners_set(swigCPtr, this, value);
  }

  public int getNumlisteners() {
    return FMODStudioJNI.FMOD_DSP_PARAMETER_3DATTRIBUTES_MULTI_numlisteners_get(swigCPtr, this);
  }

  public void setRelative(FMOD_3D_ATTRIBUTES value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_3DATTRIBUTES_MULTI_relative_set(swigCPtr, this, FMOD_3D_ATTRIBUTES.getCPtr(value), value);
  }

  public FMOD_3D_ATTRIBUTES getRelative() {
    long cPtr = FMODStudioJNI.FMOD_DSP_PARAMETER_3DATTRIBUTES_MULTI_relative_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_3D_ATTRIBUTES(cPtr, false);
  }

  public void setWeight(SWIGTYPE_p_float value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_3DATTRIBUTES_MULTI_weight_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getWeight() {
    long cPtr = FMODStudioJNI.FMOD_DSP_PARAMETER_3DATTRIBUTES_MULTI_weight_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setAbsolute(FMOD_3D_ATTRIBUTES value) {
    FMODStudioJNI.FMOD_DSP_PARAMETER_3DATTRIBUTES_MULTI_absolute_set(swigCPtr, this, FMOD_3D_ATTRIBUTES.getCPtr(value), value);
  }

  public FMOD_3D_ATTRIBUTES getAbsolute() {
    long cPtr = FMODStudioJNI.FMOD_DSP_PARAMETER_3DATTRIBUTES_MULTI_absolute_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_3D_ATTRIBUTES(cPtr, false);
  }

  public FMOD_DSP_PARAMETER_3DATTRIBUTES_MULTI() {
    this(FMODStudioJNI.new_FMOD_DSP_PARAMETER_3DATTRIBUTES_MULTI(), true);
  }

}
