package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_PARAMETER_TYPE {
  public final static FMOD_DSP_PARAMETER_TYPE FMOD_DSP_PARAMETER_TYPE_FLOAT = new FMOD_DSP_PARAMETER_TYPE("FMOD_DSP_PARAMETER_TYPE_FLOAT");
  public final static FMOD_DSP_PARAMETER_TYPE FMOD_DSP_PARAMETER_TYPE_INT = new FMOD_DSP_PARAMETER_TYPE("FMOD_DSP_PARAMETER_TYPE_INT");
  public final static FMOD_DSP_PARAMETER_TYPE FMOD_DSP_PARAMETER_TYPE_BOOL = new FMOD_DSP_PARAMETER_TYPE("FMOD_DSP_PARAMETER_TYPE_BOOL");
  public final static FMOD_DSP_PARAMETER_TYPE FMOD_DSP_PARAMETER_TYPE_DATA = new FMOD_DSP_PARAMETER_TYPE("FMOD_DSP_PARAMETER_TYPE_DATA");
  public final static FMOD_DSP_PARAMETER_TYPE FMOD_DSP_PARAMETER_TYPE_MAX = new FMOD_DSP_PARAMETER_TYPE("FMOD_DSP_PARAMETER_TYPE_MAX");
  public final static FMOD_DSP_PARAMETER_TYPE FMOD_DSP_PARAMETER_TYPE_FORCEINT = new FMOD_DSP_PARAMETER_TYPE("FMOD_DSP_PARAMETER_TYPE_FORCEINT", FMODStudioJNI.FMOD_DSP_PARAMETER_TYPE_FORCEINT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_PARAMETER_TYPE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_PARAMETER_TYPE.class + " with value " + swigValue);
  }

  private FMOD_DSP_PARAMETER_TYPE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_PARAMETER_TYPE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_PARAMETER_TYPE(String swigName, FMOD_DSP_PARAMETER_TYPE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_PARAMETER_TYPE[] swigValues = { FMOD_DSP_PARAMETER_TYPE_FLOAT, FMOD_DSP_PARAMETER_TYPE_INT, FMOD_DSP_PARAMETER_TYPE_BOOL, FMOD_DSP_PARAMETER_TYPE_DATA, FMOD_DSP_PARAMETER_TYPE_MAX, FMOD_DSP_PARAMETER_TYPE_FORCEINT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

