package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_LIMITER {
  public final static FMOD_DSP_LIMITER FMOD_DSP_LIMITER_RELEASETIME = new FMOD_DSP_LIMITER("FMOD_DSP_LIMITER_RELEASETIME");
  public final static FMOD_DSP_LIMITER FMOD_DSP_LIMITER_CEILING = new FMOD_DSP_LIMITER("FMOD_DSP_LIMITER_CEILING");
  public final static FMOD_DSP_LIMITER FMOD_DSP_LIMITER_MAXIMIZERGAIN = new FMOD_DSP_LIMITER("FMOD_DSP_LIMITER_MAXIMIZERGAIN");
  public final static FMOD_DSP_LIMITER FMOD_DSP_LIMITER_MODE = new FMOD_DSP_LIMITER("FMOD_DSP_LIMITER_MODE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_LIMITER swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_LIMITER.class + " with value " + swigValue);
  }

  private FMOD_DSP_LIMITER(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_LIMITER(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_LIMITER(String swigName, FMOD_DSP_LIMITER swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_LIMITER[] swigValues = { FMOD_DSP_LIMITER_RELEASETIME, FMOD_DSP_LIMITER_CEILING, FMOD_DSP_LIMITER_MAXIMIZERGAIN, FMOD_DSP_LIMITER_MODE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

