package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_CONVOLUTION_REVERB {
  public final static FMOD_DSP_CONVOLUTION_REVERB FMOD_DSP_CONVOLUTION_REVERB_PARAM_IR = new FMOD_DSP_CONVOLUTION_REVERB("FMOD_DSP_CONVOLUTION_REVERB_PARAM_IR");
  public final static FMOD_DSP_CONVOLUTION_REVERB FMOD_DSP_CONVOLUTION_REVERB_PARAM_WET = new FMOD_DSP_CONVOLUTION_REVERB("FMOD_DSP_CONVOLUTION_REVERB_PARAM_WET");
  public final static FMOD_DSP_CONVOLUTION_REVERB FMOD_DSP_CONVOLUTION_REVERB_PARAM_DRY = new FMOD_DSP_CONVOLUTION_REVERB("FMOD_DSP_CONVOLUTION_REVERB_PARAM_DRY");
  public final static FMOD_DSP_CONVOLUTION_REVERB FMOD_DSP_CONVOLUTION_REVERB_PARAM_LINKED = new FMOD_DSP_CONVOLUTION_REVERB("FMOD_DSP_CONVOLUTION_REVERB_PARAM_LINKED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_CONVOLUTION_REVERB swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_CONVOLUTION_REVERB.class + " with value " + swigValue);
  }

  private FMOD_DSP_CONVOLUTION_REVERB(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_CONVOLUTION_REVERB(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_CONVOLUTION_REVERB(String swigName, FMOD_DSP_CONVOLUTION_REVERB swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_CONVOLUTION_REVERB[] swigValues = { FMOD_DSP_CONVOLUTION_REVERB_PARAM_IR, FMOD_DSP_CONVOLUTION_REVERB_PARAM_WET, FMOD_DSP_CONVOLUTION_REVERB_PARAM_DRY, FMOD_DSP_CONVOLUTION_REVERB_PARAM_LINKED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

