package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_COMPRESSOR {
  public final static FMOD_DSP_COMPRESSOR FMOD_DSP_COMPRESSOR_THRESHOLD = new FMOD_DSP_COMPRESSOR("FMOD_DSP_COMPRESSOR_THRESHOLD");
  public final static FMOD_DSP_COMPRESSOR FMOD_DSP_COMPRESSOR_RATIO = new FMOD_DSP_COMPRESSOR("FMOD_DSP_COMPRESSOR_RATIO");
  public final static FMOD_DSP_COMPRESSOR FMOD_DSP_COMPRESSOR_ATTACK = new FMOD_DSP_COMPRESSOR("FMOD_DSP_COMPRESSOR_ATTACK");
  public final static FMOD_DSP_COMPRESSOR FMOD_DSP_COMPRESSOR_RELEASE = new FMOD_DSP_COMPRESSOR("FMOD_DSP_COMPRESSOR_RELEASE");
  public final static FMOD_DSP_COMPRESSOR FMOD_DSP_COMPRESSOR_GAINMAKEUP = new FMOD_DSP_COMPRESSOR("FMOD_DSP_COMPRESSOR_GAINMAKEUP");
  public final static FMOD_DSP_COMPRESSOR FMOD_DSP_COMPRESSOR_USESIDECHAIN = new FMOD_DSP_COMPRESSOR("FMOD_DSP_COMPRESSOR_USESIDECHAIN");
  public final static FMOD_DSP_COMPRESSOR FMOD_DSP_COMPRESSOR_LINKED = new FMOD_DSP_COMPRESSOR("FMOD_DSP_COMPRESSOR_LINKED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_COMPRESSOR swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_COMPRESSOR.class + " with value " + swigValue);
  }

  private FMOD_DSP_COMPRESSOR(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_COMPRESSOR(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_COMPRESSOR(String swigName, FMOD_DSP_COMPRESSOR swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_COMPRESSOR[] swigValues = { FMOD_DSP_COMPRESSOR_THRESHOLD, FMOD_DSP_COMPRESSOR_RATIO, FMOD_DSP_COMPRESSOR_ATTACK, FMOD_DSP_COMPRESSOR_RELEASE, FMOD_DSP_COMPRESSOR_GAINMAKEUP, FMOD_DSP_COMPRESSOR_USESIDECHAIN, FMOD_DSP_COMPRESSOR_LINKED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

