package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_PAN_SURROUND_FLAGS {
  public final static FMOD_DSP_PAN_SURROUND_FLAGS FMOD_DSP_PAN_SURROUND_DEFAULT = new FMOD_DSP_PAN_SURROUND_FLAGS("FMOD_DSP_PAN_SURROUND_DEFAULT", FMODStudioJNI.FMOD_DSP_PAN_SURROUND_DEFAULT_get());
  public final static FMOD_DSP_PAN_SURROUND_FLAGS FMOD_DSP_PAN_SURROUND_ROTATION_NOT_BIASED = new FMOD_DSP_PAN_SURROUND_FLAGS("FMOD_DSP_PAN_SURROUND_ROTATION_NOT_BIASED", FMODStudioJNI.FMOD_DSP_PAN_SURROUND_ROTATION_NOT_BIASED_get());
  public final static FMOD_DSP_PAN_SURROUND_FLAGS FMOD_DSP_PAN_SURROUND_FLAGS_FORCEINT = new FMOD_DSP_PAN_SURROUND_FLAGS("FMOD_DSP_PAN_SURROUND_FLAGS_FORCEINT", FMODStudioJNI.FMOD_DSP_PAN_SURROUND_FLAGS_FORCEINT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_PAN_SURROUND_FLAGS swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_PAN_SURROUND_FLAGS.class + " with value " + swigValue);
  }

  private FMOD_DSP_PAN_SURROUND_FLAGS(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_PAN_SURROUND_FLAGS(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_PAN_SURROUND_FLAGS(String swigName, FMOD_DSP_PAN_SURROUND_FLAGS swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_PAN_SURROUND_FLAGS[] swigValues = { FMOD_DSP_PAN_SURROUND_DEFAULT, FMOD_DSP_PAN_SURROUND_ROTATION_NOT_BIASED, FMOD_DSP_PAN_SURROUND_FLAGS_FORCEINT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

