package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_DSP_STATE_PAN_FUNCTIONS {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_DSP_STATE_PAN_FUNCTIONS(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_DSP_STATE_PAN_FUNCTIONS obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_DSP_STATE_PAN_FUNCTIONS obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_DSP_STATE_PAN_FUNCTIONS(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSummonomatrix(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_enum_FMOD_SPEAKERMODE_float_float_p_float__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_STATE_PAN_FUNCTIONS_summonomatrix_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_enum_FMOD_SPEAKERMODE_float_float_p_float__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_enum_FMOD_SPEAKERMODE_float_float_p_float__FMOD_RESULT getSummonomatrix() {
    long cPtr = FMODStudioJNI.FMOD_DSP_STATE_PAN_FUNCTIONS_summonomatrix_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_enum_FMOD_SPEAKERMODE_float_float_p_float__FMOD_RESULT(cPtr, false);
  }

  public void setSumstereomatrix(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_enum_FMOD_SPEAKERMODE_float_float_float_int_p_float__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_STATE_PAN_FUNCTIONS_sumstereomatrix_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_enum_FMOD_SPEAKERMODE_float_float_float_int_p_float__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_enum_FMOD_SPEAKERMODE_float_float_float_int_p_float__FMOD_RESULT getSumstereomatrix() {
    long cPtr = FMODStudioJNI.FMOD_DSP_STATE_PAN_FUNCTIONS_sumstereomatrix_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_enum_FMOD_SPEAKERMODE_float_float_float_int_p_float__FMOD_RESULT(cPtr, false);
  }

  public void setSumsurroundmatrix(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_enum_FMOD_SPEAKERMODE_enum_FMOD_SPEAKERMODE_float_float_float_float_float_int_p_float_enum_FMOD_DSP_PAN_SURROUND_FLAGS__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_STATE_PAN_FUNCTIONS_sumsurroundmatrix_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_enum_FMOD_SPEAKERMODE_enum_FMOD_SPEAKERMODE_float_float_float_float_float_int_p_float_enum_FMOD_DSP_PAN_SURROUND_FLAGS__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_enum_FMOD_SPEAKERMODE_enum_FMOD_SPEAKERMODE_float_float_float_float_float_int_p_float_enum_FMOD_DSP_PAN_SURROUND_FLAGS__FMOD_RESULT getSumsurroundmatrix() {
    long cPtr = FMODStudioJNI.FMOD_DSP_STATE_PAN_FUNCTIONS_sumsurroundmatrix_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_enum_FMOD_SPEAKERMODE_enum_FMOD_SPEAKERMODE_float_float_float_float_float_int_p_float_enum_FMOD_DSP_PAN_SURROUND_FLAGS__FMOD_RESULT(cPtr, false);
  }

  public void setSummonotosurroundmatrix(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_enum_FMOD_SPEAKERMODE_float_float_float_float_int_p_float__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_STATE_PAN_FUNCTIONS_summonotosurroundmatrix_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_enum_FMOD_SPEAKERMODE_float_float_float_float_int_p_float__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_enum_FMOD_SPEAKERMODE_float_float_float_float_int_p_float__FMOD_RESULT getSummonotosurroundmatrix() {
    long cPtr = FMODStudioJNI.FMOD_DSP_STATE_PAN_FUNCTIONS_summonotosurroundmatrix_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_enum_FMOD_SPEAKERMODE_float_float_float_float_int_p_float__FMOD_RESULT(cPtr, false);
  }

  public void setSumstereotosurroundmatrix(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_enum_FMOD_SPEAKERMODE_float_float_float_float_float_int_p_float__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_STATE_PAN_FUNCTIONS_sumstereotosurroundmatrix_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_enum_FMOD_SPEAKERMODE_float_float_float_float_float_int_p_float__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_enum_FMOD_SPEAKERMODE_float_float_float_float_float_int_p_float__FMOD_RESULT getSumstereotosurroundmatrix() {
    long cPtr = FMODStudioJNI.FMOD_DSP_STATE_PAN_FUNCTIONS_sumstereotosurroundmatrix_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_enum_FMOD_SPEAKERMODE_float_float_float_float_float_int_p_float__FMOD_RESULT(cPtr, false);
  }

  public void setGetrolloffgain(SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_enum_FMOD_DSP_PAN_3D_ROLLOFF_TYPE_float_float_float_p_float__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_DSP_STATE_PAN_FUNCTIONS_getrolloffgain_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_enum_FMOD_DSP_PAN_3D_ROLLOFF_TYPE_float_float_float_p_float__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_enum_FMOD_DSP_PAN_3D_ROLLOFF_TYPE_float_float_float_p_float__FMOD_RESULT getGetrolloffgain() {
    long cPtr = FMODStudioJNI.FMOD_DSP_STATE_PAN_FUNCTIONS_getrolloffgain_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_DSP_STATE_enum_FMOD_DSP_PAN_3D_ROLLOFF_TYPE_float_float_float_p_float__FMOD_RESULT(cPtr, false);
  }

  public FMOD_DSP_STATE_PAN_FUNCTIONS() {
    this(FMODStudioJNI.new_FMOD_DSP_STATE_PAN_FUNCTIONS(), true);
  }

}
