package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_OUTPUT_STATE {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_OUTPUT_STATE(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_OUTPUT_STATE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_OUTPUT_STATE obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_OUTPUT_STATE(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPlugindata(SWIGTYPE_p_void value) {
    FMODStudioJNI.FMOD_OUTPUT_STATE_plugindata_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getPlugindata() {
    long cPtr = FMODStudioJNI.FMOD_OUTPUT_STATE_plugindata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setReadfrommixer(SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_void_unsigned_int__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_OUTPUT_STATE_readfrommixer_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_void_unsigned_int__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_void_unsigned_int__FMOD_RESULT getReadfrommixer() {
    long cPtr = FMODStudioJNI.FMOD_OUTPUT_STATE_readfrommixer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_p_void_unsigned_int__FMOD_RESULT(cPtr, false);
  }

  public void setAlloc(SWIGTYPE_p_f_unsigned_int_unsigned_int_p_q_const__char_int__p_void value) {
    FMODStudioJNI.FMOD_OUTPUT_STATE_alloc_set(swigCPtr, this, SWIGTYPE_p_f_unsigned_int_unsigned_int_p_q_const__char_int__p_void.getCPtr(value));
  }

  public SWIGTYPE_p_f_unsigned_int_unsigned_int_p_q_const__char_int__p_void getAlloc() {
    long cPtr = FMODStudioJNI.FMOD_OUTPUT_STATE_alloc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_unsigned_int_unsigned_int_p_q_const__char_int__p_void(cPtr, false);
  }

  public void setFree(SWIGTYPE_p_f_p_void_p_q_const__char_int__void value) {
    FMODStudioJNI.FMOD_OUTPUT_STATE_free_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_q_const__char_int__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_q_const__char_int__void getFree() {
    long cPtr = FMODStudioJNI.FMOD_OUTPUT_STATE_free_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_q_const__char_int__void(cPtr, false);
  }

  public void setLog(SWIGTYPE_p_f_unsigned_int_p_q_const__char_int_p_q_const__char_p_q_const__char_v_______void value) {
    FMODStudioJNI.FMOD_OUTPUT_STATE_log_set(swigCPtr, this, SWIGTYPE_p_f_unsigned_int_p_q_const__char_int_p_q_const__char_p_q_const__char_v_______void.getCPtr(value));
  }

  public SWIGTYPE_p_f_unsigned_int_p_q_const__char_int_p_q_const__char_p_q_const__char_v_______void getLog() {
    long cPtr = FMODStudioJNI.FMOD_OUTPUT_STATE_log_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_unsigned_int_p_q_const__char_int_p_q_const__char_p_q_const__char_v_______void(cPtr, false);
  }

  public void setCopyport(SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_int_p_void_unsigned_int__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_OUTPUT_STATE_copyport_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_int_p_void_unsigned_int__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_int_p_void_unsigned_int__FMOD_RESULT getCopyport() {
    long cPtr = FMODStudioJNI.FMOD_OUTPUT_STATE_copyport_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE_int_p_void_unsigned_int__FMOD_RESULT(cPtr, false);
  }

  public void setRequestreset(SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT value) {
    FMODStudioJNI.FMOD_OUTPUT_STATE_requestreset_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT getRequestreset() {
    long cPtr = FMODStudioJNI.FMOD_OUTPUT_STATE_requestreset_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_FMOD_OUTPUT_STATE__FMOD_RESULT(cPtr, false);
  }

  public FMOD_OUTPUT_STATE() {
    this(FMODStudioJNI.new_FMOD_OUTPUT_STATE(), true);
  }

}
