package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_DSP_LOUDNESS_METER_INFO_TYPE {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_DSP_LOUDNESS_METER_INFO_TYPE(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_DSP_LOUDNESS_METER_INFO_TYPE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_DSP_LOUDNESS_METER_INFO_TYPE obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_DSP_LOUDNESS_METER_INFO_TYPE(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMomentaryloudness(float value) {
    FMODStudioJNI.FMOD_DSP_LOUDNESS_METER_INFO_TYPE_momentaryloudness_set(swigCPtr, this, value);
  }

  public float getMomentaryloudness() {
    return FMODStudioJNI.FMOD_DSP_LOUDNESS_METER_INFO_TYPE_momentaryloudness_get(swigCPtr, this);
  }

  public void setShorttermloudness(float value) {
    FMODStudioJNI.FMOD_DSP_LOUDNESS_METER_INFO_TYPE_shorttermloudness_set(swigCPtr, this, value);
  }

  public float getShorttermloudness() {
    return FMODStudioJNI.FMOD_DSP_LOUDNESS_METER_INFO_TYPE_shorttermloudness_get(swigCPtr, this);
  }

  public void setIntegratedloudness(float value) {
    FMODStudioJNI.FMOD_DSP_LOUDNESS_METER_INFO_TYPE_integratedloudness_set(swigCPtr, this, value);
  }

  public float getIntegratedloudness() {
    return FMODStudioJNI.FMOD_DSP_LOUDNESS_METER_INFO_TYPE_integratedloudness_get(swigCPtr, this);
  }

  public void setLoudness10thpercentile(float value) {
    FMODStudioJNI.FMOD_DSP_LOUDNESS_METER_INFO_TYPE_loudness10thpercentile_set(swigCPtr, this, value);
  }

  public float getLoudness10thpercentile() {
    return FMODStudioJNI.FMOD_DSP_LOUDNESS_METER_INFO_TYPE_loudness10thpercentile_get(swigCPtr, this);
  }

  public void setLoudness95thpercentile(float value) {
    FMODStudioJNI.FMOD_DSP_LOUDNESS_METER_INFO_TYPE_loudness95thpercentile_set(swigCPtr, this, value);
  }

  public float getLoudness95thpercentile() {
    return FMODStudioJNI.FMOD_DSP_LOUDNESS_METER_INFO_TYPE_loudness95thpercentile_get(swigCPtr, this);
  }

  public void setLoudnesshistogram(SWIGTYPE_p_float value) {
    FMODStudioJNI.FMOD_DSP_LOUDNESS_METER_INFO_TYPE_loudnesshistogram_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getLoudnesshistogram() {
    long cPtr = FMODStudioJNI.FMOD_DSP_LOUDNESS_METER_INFO_TYPE_loudnesshistogram_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setMaxtruepeak(float value) {
    FMODStudioJNI.FMOD_DSP_LOUDNESS_METER_INFO_TYPE_maxtruepeak_set(swigCPtr, this, value);
  }

  public float getMaxtruepeak() {
    return FMODStudioJNI.FMOD_DSP_LOUDNESS_METER_INFO_TYPE_maxtruepeak_get(swigCPtr, this);
  }

  public void setMaxmomentaryloudness(float value) {
    FMODStudioJNI.FMOD_DSP_LOUDNESS_METER_INFO_TYPE_maxmomentaryloudness_set(swigCPtr, this, value);
  }

  public float getMaxmomentaryloudness() {
    return FMODStudioJNI.FMOD_DSP_LOUDNESS_METER_INFO_TYPE_maxmomentaryloudness_get(swigCPtr, this);
  }

  public FMOD_DSP_LOUDNESS_METER_INFO_TYPE() {
    this(FMODStudioJNI.new_FMOD_DSP_LOUDNESS_METER_INFO_TYPE(), true);
  }

}
