package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_STUDIO_BUFFER_USAGE {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_STUDIO_BUFFER_USAGE(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_STUDIO_BUFFER_USAGE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_STUDIO_BUFFER_USAGE obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_STUDIO_BUFFER_USAGE(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStudiocommandqueue(FMOD_STUDIO_BUFFER_INFO value) {
    FMODStudioJNI.FMOD_STUDIO_BUFFER_USAGE_studiocommandqueue_set(swigCPtr, this, FMOD_STUDIO_BUFFER_INFO.getCPtr(value), value);
  }

  public FMOD_STUDIO_BUFFER_INFO getStudiocommandqueue() {
    long cPtr = FMODStudioJNI.FMOD_STUDIO_BUFFER_USAGE_studiocommandqueue_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_STUDIO_BUFFER_INFO(cPtr, false);
  }

  public void setStudiohandle(FMOD_STUDIO_BUFFER_INFO value) {
    FMODStudioJNI.FMOD_STUDIO_BUFFER_USAGE_studiohandle_set(swigCPtr, this, FMOD_STUDIO_BUFFER_INFO.getCPtr(value), value);
  }

  public FMOD_STUDIO_BUFFER_INFO getStudiohandle() {
    long cPtr = FMODStudioJNI.FMOD_STUDIO_BUFFER_USAGE_studiohandle_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_STUDIO_BUFFER_INFO(cPtr, false);
  }

  public FMOD_STUDIO_BUFFER_USAGE() {
    this(FMODStudioJNI.new_FMOD_STUDIO_BUFFER_USAGE(), true);
  }

}
