package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_ECHO {
  public final static FMOD_DSP_ECHO FMOD_DSP_ECHO_DELAY = new FMOD_DSP_ECHO("FMOD_DSP_ECHO_DELAY");
  public final static FMOD_DSP_ECHO FMOD_DSP_ECHO_FEEDBACK = new FMOD_DSP_ECHO("FMOD_DSP_ECHO_FEEDBACK");
  public final static FMOD_DSP_ECHO FMOD_DSP_ECHO_DRYLEVEL = new FMOD_DSP_ECHO("FMOD_DSP_ECHO_DRYLEVEL");
  public final static FMOD_DSP_ECHO FMOD_DSP_ECHO_WETLEVEL = new FMOD_DSP_ECHO("FMOD_DSP_ECHO_WETLEVEL");
  public final static FMOD_DSP_ECHO FMOD_DSP_ECHO_DELAYCHANGEMODE = new FMOD_DSP_ECHO("FMOD_DSP_ECHO_DELAYCHANGEMODE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_ECHO swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_ECHO.class + " with value " + swigValue);
  }

  private FMOD_DSP_ECHO(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_ECHO(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_ECHO(String swigName, FMOD_DSP_ECHO swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_ECHO[] swigValues = { FMOD_DSP_ECHO_DELAY, FMOD_DSP_ECHO_FEEDBACK, FMOD_DSP_ECHO_DRYLEVEL, FMOD_DSP_ECHO_WETLEVEL, FMOD_DSP_ECHO_DELAYCHANGEMODE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

