package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_STUDIO_BUFFER_INFO {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_STUDIO_BUFFER_INFO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_STUDIO_BUFFER_INFO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_STUDIO_BUFFER_INFO obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_STUDIO_BUFFER_INFO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCurrentusage(int value) {
    FMODStudioJNI.FMOD_STUDIO_BUFFER_INFO_currentusage_set(swigCPtr, this, value);
  }

  public int getCurrentusage() {
    return FMODStudioJNI.FMOD_STUDIO_BUFFER_INFO_currentusage_get(swigCPtr, this);
  }

  public void setPeakusage(int value) {
    FMODStudioJNI.FMOD_STUDIO_BUFFER_INFO_peakusage_set(swigCPtr, this, value);
  }

  public int getPeakusage() {
    return FMODStudioJNI.FMOD_STUDIO_BUFFER_INFO_peakusage_get(swigCPtr, this);
  }

  public void setCapacity(int value) {
    FMODStudioJNI.FMOD_STUDIO_BUFFER_INFO_capacity_set(swigCPtr, this, value);
  }

  public int getCapacity() {
    return FMODStudioJNI.FMOD_STUDIO_BUFFER_INFO_capacity_get(swigCPtr, this);
  }

  public void setStallcount(int value) {
    FMODStudioJNI.FMOD_STUDIO_BUFFER_INFO_stallcount_set(swigCPtr, this, value);
  }

  public int getStallcount() {
    return FMODStudioJNI.FMOD_STUDIO_BUFFER_INFO_stallcount_get(swigCPtr, this);
  }

  public void setStalltime(float value) {
    FMODStudioJNI.FMOD_STUDIO_BUFFER_INFO_stalltime_set(swigCPtr, this, value);
  }

  public float getStalltime() {
    return FMODStudioJNI.FMOD_STUDIO_BUFFER_INFO_stalltime_get(swigCPtr, this);
  }

  public FMOD_STUDIO_BUFFER_INFO() {
    this(FMODStudioJNI.new_FMOD_STUDIO_BUFFER_INFO(), true);
  }

}
