package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FMOD_DSP_DATA_PARAMETER_INFO {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_DSP_DATA_PARAMETER_INFO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_DSP_DATA_PARAMETER_INFO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FMOD_DSP_DATA_PARAMETER_INFO obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODStudioJNI.delete_FMOD_DSP_DATA_PARAMETER_INFO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData(SWIGTYPE_p_void value) {
    FMODStudioJNI.FMOD_DSP_DATA_PARAMETER_INFO_data_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getData() {
    long cPtr = FMODStudioJNI.FMOD_DSP_DATA_PARAMETER_INFO_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setLength(long value) {
    FMODStudioJNI.FMOD_DSP_DATA_PARAMETER_INFO_length_set(swigCPtr, this, value);
  }

  public long getLength() {
    return FMODStudioJNI.FMOD_DSP_DATA_PARAMETER_INFO_length_get(swigCPtr, this);
  }

  public void setIndex(int value) {
    FMODStudioJNI.FMOD_DSP_DATA_PARAMETER_INFO_index_set(swigCPtr, this, value);
  }

  public int getIndex() {
    return FMODStudioJNI.FMOD_DSP_DATA_PARAMETER_INFO_index_get(swigCPtr, this);
  }

  public FMOD_DSP_DATA_PARAMETER_INFO() {
    this(FMODStudioJNI.new_FMOD_DSP_DATA_PARAMETER_INFO(), true);
  }

}
