package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_ITECHO {
  public final static FMOD_DSP_ITECHO FMOD_DSP_ITECHO_WETDRYMIX = new FMOD_DSP_ITECHO("FMOD_DSP_ITECHO_WETDRYMIX");
  public final static FMOD_DSP_ITECHO FMOD_DSP_ITECHO_FEEDBACK = new FMOD_DSP_ITECHO("FMOD_DSP_ITECHO_FEEDBACK");
  public final static FMOD_DSP_ITECHO FMOD_DSP_ITECHO_LEFTDELAY = new FMOD_DSP_ITECHO("FMOD_DSP_ITECHO_LEFTDELAY");
  public final static FMOD_DSP_ITECHO FMOD_DSP_ITECHO_RIGHTDELAY = new FMOD_DSP_ITECHO("FMOD_DSP_ITECHO_RIGHTDELAY");
  public final static FMOD_DSP_ITECHO FMOD_DSP_ITECHO_PANDELAY = new FMOD_DSP_ITECHO("FMOD_DSP_ITECHO_PANDELAY");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_ITECHO swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_ITECHO.class + " with value " + swigValue);
  }

  private FMOD_DSP_ITECHO(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_ITECHO(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_ITECHO(String swigName, FMOD_DSP_ITECHO swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_ITECHO[] swigValues = { FMOD_DSP_ITECHO_WETDRYMIX, FMOD_DSP_ITECHO_FEEDBACK, FMOD_DSP_ITECHO_LEFTDELAY, FMOD_DSP_ITECHO_RIGHTDELAY, FMOD_DSP_ITECHO_PANDELAY };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

