package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_PAN {
  public final static FMOD_DSP_PAN FMOD_DSP_PAN_MODE = new FMOD_DSP_PAN("FMOD_DSP_PAN_MODE");
  public final static FMOD_DSP_PAN FMOD_DSP_PAN_2D_STEREO_POSITION = new FMOD_DSP_PAN("FMOD_DSP_PAN_2D_STEREO_POSITION");
  public final static FMOD_DSP_PAN FMOD_DSP_PAN_2D_DIRECTION = new FMOD_DSP_PAN("FMOD_DSP_PAN_2D_DIRECTION");
  public final static FMOD_DSP_PAN FMOD_DSP_PAN_2D_EXTENT = new FMOD_DSP_PAN("FMOD_DSP_PAN_2D_EXTENT");
  public final static FMOD_DSP_PAN FMOD_DSP_PAN_2D_ROTATION = new FMOD_DSP_PAN("FMOD_DSP_PAN_2D_ROTATION");
  public final static FMOD_DSP_PAN FMOD_DSP_PAN_2D_LFE_LEVEL = new FMOD_DSP_PAN("FMOD_DSP_PAN_2D_LFE_LEVEL");
  public final static FMOD_DSP_PAN FMOD_DSP_PAN_2D_STEREO_MODE = new FMOD_DSP_PAN("FMOD_DSP_PAN_2D_STEREO_MODE");
  public final static FMOD_DSP_PAN FMOD_DSP_PAN_2D_STEREO_SEPARATION = new FMOD_DSP_PAN("FMOD_DSP_PAN_2D_STEREO_SEPARATION");
  public final static FMOD_DSP_PAN FMOD_DSP_PAN_2D_STEREO_AXIS = new FMOD_DSP_PAN("FMOD_DSP_PAN_2D_STEREO_AXIS");
  public final static FMOD_DSP_PAN FMOD_DSP_PAN_ENABLED_SPEAKERS = new FMOD_DSP_PAN("FMOD_DSP_PAN_ENABLED_SPEAKERS");
  public final static FMOD_DSP_PAN FMOD_DSP_PAN_3D_POSITION = new FMOD_DSP_PAN("FMOD_DSP_PAN_3D_POSITION");
  public final static FMOD_DSP_PAN FMOD_DSP_PAN_3D_ROLLOFF = new FMOD_DSP_PAN("FMOD_DSP_PAN_3D_ROLLOFF");
  public final static FMOD_DSP_PAN FMOD_DSP_PAN_3D_MIN_DISTANCE = new FMOD_DSP_PAN("FMOD_DSP_PAN_3D_MIN_DISTANCE");
  public final static FMOD_DSP_PAN FMOD_DSP_PAN_3D_MAX_DISTANCE = new FMOD_DSP_PAN("FMOD_DSP_PAN_3D_MAX_DISTANCE");
  public final static FMOD_DSP_PAN FMOD_DSP_PAN_3D_EXTENT_MODE = new FMOD_DSP_PAN("FMOD_DSP_PAN_3D_EXTENT_MODE");
  public final static FMOD_DSP_PAN FMOD_DSP_PAN_3D_SOUND_SIZE = new FMOD_DSP_PAN("FMOD_DSP_PAN_3D_SOUND_SIZE");
  public final static FMOD_DSP_PAN FMOD_DSP_PAN_3D_MIN_EXTENT = new FMOD_DSP_PAN("FMOD_DSP_PAN_3D_MIN_EXTENT");
  public final static FMOD_DSP_PAN FMOD_DSP_PAN_3D_PAN_BLEND = new FMOD_DSP_PAN("FMOD_DSP_PAN_3D_PAN_BLEND");
  public final static FMOD_DSP_PAN FMOD_DSP_PAN_LFE_UPMIX_ENABLED = new FMOD_DSP_PAN("FMOD_DSP_PAN_LFE_UPMIX_ENABLED");
  public final static FMOD_DSP_PAN FMOD_DSP_PAN_OVERALL_GAIN = new FMOD_DSP_PAN("FMOD_DSP_PAN_OVERALL_GAIN");
  public final static FMOD_DSP_PAN FMOD_DSP_PAN_SURROUND_SPEAKER_MODE = new FMOD_DSP_PAN("FMOD_DSP_PAN_SURROUND_SPEAKER_MODE");
  public final static FMOD_DSP_PAN FMOD_DSP_PAN_2D_HEIGHT_BLEND = new FMOD_DSP_PAN("FMOD_DSP_PAN_2D_HEIGHT_BLEND");
  public final static FMOD_DSP_PAN FMOD_DSP_PAN_ATTENUATION_RANGE = new FMOD_DSP_PAN("FMOD_DSP_PAN_ATTENUATION_RANGE");
  public final static FMOD_DSP_PAN FMOD_DSP_PAN_OVERRIDE_RANGE = new FMOD_DSP_PAN("FMOD_DSP_PAN_OVERRIDE_RANGE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_PAN swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_PAN.class + " with value " + swigValue);
  }

  private FMOD_DSP_PAN(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_PAN(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_PAN(String swigName, FMOD_DSP_PAN swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_PAN[] swigValues = { FMOD_DSP_PAN_MODE, FMOD_DSP_PAN_2D_STEREO_POSITION, FMOD_DSP_PAN_2D_DIRECTION, FMOD_DSP_PAN_2D_EXTENT, FMOD_DSP_PAN_2D_ROTATION, FMOD_DSP_PAN_2D_LFE_LEVEL, FMOD_DSP_PAN_2D_STEREO_MODE, FMOD_DSP_PAN_2D_STEREO_SEPARATION, FMOD_DSP_PAN_2D_STEREO_AXIS, FMOD_DSP_PAN_ENABLED_SPEAKERS, FMOD_DSP_PAN_3D_POSITION, FMOD_DSP_PAN_3D_ROLLOFF, FMOD_DSP_PAN_3D_MIN_DISTANCE, FMOD_DSP_PAN_3D_MAX_DISTANCE, FMOD_DSP_PAN_3D_EXTENT_MODE, FMOD_DSP_PAN_3D_SOUND_SIZE, FMOD_DSP_PAN_3D_MIN_EXTENT, FMOD_DSP_PAN_3D_PAN_BLEND, FMOD_DSP_PAN_LFE_UPMIX_ENABLED, FMOD_DSP_PAN_OVERALL_GAIN, FMOD_DSP_PAN_SURROUND_SPEAKER_MODE, FMOD_DSP_PAN_2D_HEIGHT_BLEND, FMOD_DSP_PAN_ATTENUATION_RANGE, FMOD_DSP_PAN_OVERRIDE_RANGE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

