package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FMOD_DSP_SFXREVERB {
  public final static FMOD_DSP_SFXREVERB FMOD_DSP_SFXREVERB_DECAYTIME = new FMOD_DSP_SFXREVERB("FMOD_DSP_SFXREVERB_DECAYTIME");
  public final static FMOD_DSP_SFXREVERB FMOD_DSP_SFXREVERB_EARLYDELAY = new FMOD_DSP_SFXREVERB("FMOD_DSP_SFXREVERB_EARLYDELAY");
  public final static FMOD_DSP_SFXREVERB FMOD_DSP_SFXREVERB_LATEDELAY = new FMOD_DSP_SFXREVERB("FMOD_DSP_SFXREVERB_LATEDELAY");
  public final static FMOD_DSP_SFXREVERB FMOD_DSP_SFXREVERB_HFREFERENCE = new FMOD_DSP_SFXREVERB("FMOD_DSP_SFXREVERB_HFREFERENCE");
  public final static FMOD_DSP_SFXREVERB FMOD_DSP_SFXREVERB_HFDECAYRATIO = new FMOD_DSP_SFXREVERB("FMOD_DSP_SFXREVERB_HFDECAYRATIO");
  public final static FMOD_DSP_SFXREVERB FMOD_DSP_SFXREVERB_DIFFUSION = new FMOD_DSP_SFXREVERB("FMOD_DSP_SFXREVERB_DIFFUSION");
  public final static FMOD_DSP_SFXREVERB FMOD_DSP_SFXREVERB_DENSITY = new FMOD_DSP_SFXREVERB("FMOD_DSP_SFXREVERB_DENSITY");
  public final static FMOD_DSP_SFXREVERB FMOD_DSP_SFXREVERB_LOWSHELFFREQUENCY = new FMOD_DSP_SFXREVERB("FMOD_DSP_SFXREVERB_LOWSHELFFREQUENCY");
  public final static FMOD_DSP_SFXREVERB FMOD_DSP_SFXREVERB_LOWSHELFGAIN = new FMOD_DSP_SFXREVERB("FMOD_DSP_SFXREVERB_LOWSHELFGAIN");
  public final static FMOD_DSP_SFXREVERB FMOD_DSP_SFXREVERB_HIGHCUT = new FMOD_DSP_SFXREVERB("FMOD_DSP_SFXREVERB_HIGHCUT");
  public final static FMOD_DSP_SFXREVERB FMOD_DSP_SFXREVERB_EARLYLATEMIX = new FMOD_DSP_SFXREVERB("FMOD_DSP_SFXREVERB_EARLYLATEMIX");
  public final static FMOD_DSP_SFXREVERB FMOD_DSP_SFXREVERB_WETLEVEL = new FMOD_DSP_SFXREVERB("FMOD_DSP_SFXREVERB_WETLEVEL");
  public final static FMOD_DSP_SFXREVERB FMOD_DSP_SFXREVERB_DRYLEVEL = new FMOD_DSP_SFXREVERB("FMOD_DSP_SFXREVERB_DRYLEVEL");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSP_SFXREVERB swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSP_SFXREVERB.class + " with value " + swigValue);
  }

  private FMOD_DSP_SFXREVERB(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSP_SFXREVERB(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSP_SFXREVERB(String swigName, FMOD_DSP_SFXREVERB swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSP_SFXREVERB[] swigValues = { FMOD_DSP_SFXREVERB_DECAYTIME, FMOD_DSP_SFXREVERB_EARLYDELAY, FMOD_DSP_SFXREVERB_LATEDELAY, FMOD_DSP_SFXREVERB_HFREFERENCE, FMOD_DSP_SFXREVERB_HFDECAYRATIO, FMOD_DSP_SFXREVERB_DIFFUSION, FMOD_DSP_SFXREVERB_DENSITY, FMOD_DSP_SFXREVERB_LOWSHELFFREQUENCY, FMOD_DSP_SFXREVERB_LOWSHELFGAIN, FMOD_DSP_SFXREVERB_HIGHCUT, FMOD_DSP_SFXREVERB_EARLYLATEMIX, FMOD_DSP_SFXREVERB_WETLEVEL, FMOD_DSP_SFXREVERB_DRYLEVEL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

