package com.fmod;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SWIGTYPE_p_FMOD_STUDIO_LOADING_STATE {
  private transient long swigCPtr;

  protected SWIGTYPE_p_FMOD_STUDIO_LOADING_STATE(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_FMOD_STUDIO_LOADING_STATE() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_FMOD_STUDIO_LOADING_STATE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SWIGTYPE_p_FMOD_STUDIO_LOADING_STATE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

