/*
 * This source file was generated by the Gradle 'init' task
 */
package com.iwei20;

import org.junit.jupiter.api.Test;

import com.iwei20.fmod.FModStudio;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test void creationAndRelease() {

    }

}
