/*
 * This source file was generated by the Gradle 'init' task
 */
package com.iwei20;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        assertTrue(true, "someLibraryMethod should return 'true'");
    }
}
