/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    id("com.diffplug.spotless") version "7.+"
    id("net.ltgt.errorprone") version "4.+"
    id("net.ltgt.nullaway") version "2.+"
    id("com.github.spotbugs") version "6.+"
    `maven-publish`
    pmd
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    errorprone("com.uber.nullaway:nullaway:0.12.7")
    api("org.jspecify:jspecify:1.0.0")
    errorprone("com.google.errorprone:error_prone_core:2.38.0")

    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    implementation("commons-io:commons-io:2.18.0")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    implementation(files("fmod-jextract.jar")) // The FMOD and FMODStudio bindings
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()

    testLogging.showStandardStreams = true;
    jvmArgs("--enable-preview", "--enable-native-access=ALL-UNNAMED")
}

tasks.withType<JavaCompile> {
    options.getCompilerArgs().add("--enable-preview")
}

tasks.withType<JavaCompile>().configureEach {
    options.release = 21
}

nullaway {
    annotatedPackages.add("com.iwei20.fmod")
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21

    sourceSets{
        named("main") {
            java {
                srcDir("src/generated/java")
            }

            compileClasspath += files("src/generated/java")
            runtimeClasspath += files("src/generated/java")
        }
    }

}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            from(components["java"])
        }
    }

    repositories {
        mavenLocal()
    }
}

spotless {
    java {
        importOrder()
        removeUnusedImports()

        palantirJavaFormat()
        leadingTabsToSpaces(4)

        formatAnnotations()
    }
    kotlinGradle {
        trimTrailingWhitespace()
        leadingTabsToSpaces(4)
        endWithNewline()
    }
}
